= Introduction to {cstar-data-migrator}

Use {cstar-data-migrator} to migrate and validate tables between origin and target Cassandra clusters, with available logging and reconciliation support.


[[cdm-install-as-container]]
== Install {cstar-data-migrator} as a Container

Get the latest image that includes all dependencies from https://hub.docker.com/r/datastax/cassandra-data-migrator[DockerHub].

All migration tools, `cassandra-data-migrator` + `dsbulk` + `cqlsh`, are available in the `/assets/` folder of the container.

[[cdm-install-as-jar]]
== Install {cstar-data-migrator} as a JAR file

Download the *latest* JAR file from the {cstar-data-migrator} https://github.com/datastax/cassandra-data-migrator/packages/1832128[GitHub repo].
image:https://img.shields.io/github/v/release/datastax/cassandra-data-migrator?color=green[Latest release]

[NOTE]
====
Version 4.x of {cstar-data-migrator} is not backward-compatible with `*.properties` files created in previous versions, and package names have changed.
If you're starting new, use the latest released version if possible.
====

[[cdm-build-jar-local]]
== Build {cstar-data-migrator} JAR for local development (optional)

Optionally, you can build the {cstar-data-migrator} JAR for local development. You'll need https://maven.apache.org/download.cgi[Maven] 3.9.x.

Example:

[source,bash]
----
cd ~/github
git clone git@github.com:datastax/cassandra-data-migrator.git
cd cassandra-data-migrator
mvn clean package
----

The fat jar, or`cassandra-data-migrator-x.y.z.jar`, file should be present now in the `target` folder.


[[cdm-reference]]
== {cstar-data-migrator} reference

* xref:cdm-parameters.adoc#cdm-connection-params[Common connection parameters for Origin and Target]
* xref:cdm-parameters.adoc#cdm-origin-schema-params[Origin schema parameters]
* xref:cdm-parameters.adoc#cdm-target-schema-params[Target schema parameter]
* xref:cdm-parameters.adoc#cdm-auto-correction-params[Auto-correction parameters]
* xref:cdm-parameters.adoc#cdm-performance-operations-params[Performance and operations parameters]
* xref:cdm-parameters.adoc#cdm-transformation-params[Transformation parameters]
* xref:cdm-parameters.adoc#cdm-cassandra-filter-params[Cassandra filter parameters]
* xref:cdm-parameters.adoc#cdm-java-filter-params[Java filter parameters]
* xref:cdm-parameters.adoc#cdm-constant-column-feature-params[Constant column feature parameters]
* xref:cdm-parameters.adoc#cdm-explode-map-feature-params[Explode map feature parameters]
* xref:cdm-parameters.adoc#cdm-guardrail-feature-params[Guardrail feature parameters]
* xref:cdm-parameters.adoc#cdm-tls-ssl-connection-params[TLS (SSL) connection parameters]
