= Contribution guidelines
:page-tag: migration,zdm,zero-downtime,zdm-proxy,contributions

{company} {product} ({product-short}) provides a simple and reliable way for users to migrate an existing {cass-reg} or {dse} cluster to {astra-db}, or to any {cass-short} or {dse-short} cluster, without any interruption of service to the client applications and data.

{product-proxy} is open source software (OSS). We welcome contributions from the developer community via Pull Requests on a fork, for evaluation by the {product-short} team.

The code sources for additional {product} components -- including {product-utility}, {product-automation}, {cass-migrator}, and {dsbulk-migrator} -- are available in public GitHub repos, where you may submit feedback and ideas via GitHub Issues.
Code contributions for those additional components are not open for PRs at this time.

== {product-proxy} License

{product-proxy} is licensed under the open-source {product-proxy-repo}/blob/main/LICENSE[**Apache-2.0 license agreement**].

== Contributor License Agreement

Acceptance of the {company} https://cla.datastax.com/[Contributor License Agreement] (CLA) is required before we can consider accepting your {product-proxy} code contribution.
Refer to the https://cla.datastax.com/[CLA terms] and, if you agree, indicate your acceptance on each Pull Request (PR) that you submit while using the {product-proxy-repo}[{product-proxy} GitHub repository].

// You will see the CLA listed on the standard pull request checklist (TBS)
// for the {product-proxy-repo}[{product-proxy}] repository.

== {product-proxy} code contributions

The overall procedure:

. Fork the {product-proxy-repo}[{product-proxy} open-source public repo].
. Make your changes locally on your fork. Git commit and push only to your fork.
. Wait for CI to run successfully in GitHub Actions before submitting a PR.
. Submit a Pull Request (PR) with your forked updates.
As noted above, be sure to indicate in the PR's Comments your acceptance (if you agree) with the {company} https://cla.datastax.com/[Contributor License Agreement] (CLA).
. If you're not yet ready for a review, add "WIP" to the PR name to indicate it's a work in progress.
. Wait for the automated PR workflow to do some checks.
Members of the {product-proxy} community will review your PR and decide whether to approve and merge it.

In addition to potential {product-proxy} OSS code contribution, we encourage you to submit feedback and ideas via GitHub Issues in the repo, starting from {product-proxy-repo}/issues.
Add a label to help categorize the issue, such as the complexity level, component name, and other labels you'll find in the repo's Issues display.

== Submitting GitHub Issues in related public repos

The following {company} {product} GitHub repos are public.
You are welcome to read the source and submit feedback and ideas via GitHub Issues per repo.
In addition to the {product-proxy-repo}[{product-proxy}] open-source repo, refer to:

* {product-automation-repo}/issues[{product-automation}] repo for Ansible-based {product-automation} and {product-utility}.

* {cass-migrator-repo}/issues[{cass-migrator}] repo.

* {dsbulk-migrator-repo}/issues[{dsbulk-migrator}] repo.

Again, add a label to help categorize each issue, such as the complexity level, component name, and other labels you'll find in the repo's Issues display.
