= Create the target environment for your migration
:navtitle: Create target environment for migration
:page-tag: migration,zdm,zero-downtime,zdm-proxy,target

In this phase of the migration, you must create and prepare a new database (cluster) to be the target for your migration.
You must also gather authentication credentials to allow {product-proxy} and your client applications to connect to the new database.

== Prepare the target database

The preparation steps depend on your target database platform.

[tabs]
======
Use an {astra-db} database as the target::
+
--
To migrate data to an {astra-db} database, do the following:

. Sign in to your {astra-url}[{astra} account^].
+
You can use any subscription plan tier.
However, the Pay As You Go and Enterprise plans offer premium features that can facilitate your migration, including support for {sstable-sideloader}, more databases, and no automatic database hibernation.
These plans also support advanced features like customer-managed encryption keys and metrics exports.
For more information, see xref:astra-db-serverless:administration:subscription-plans.adoc[].

. xref:astra-db-serverless:databases:create-database.adoc[Create an {astra-db} Serverless database] with your preferred database name, keyspace name, region, and other details.
+
The keyspace is a handle that establishes the database's context in subsequent DDL and DML statements.
+
For multi-region clusters, {company} recommends migrating to one region first, and then xref:astra-db-serverless:databases:manage-regions.adoc[adding additional regions] after the initial migration is complete.

. When your database reaches **Active** status, xref:astra-db-serverless:administration:manage-application-tokens.adoc[create an application token] with a role like *Read/Write User* or **Database Administrator**, and then store the credentials (Client ID, Client Secret, and Token) securely.
+
These credentials are used by the client application, {product-proxy}, and {product-automation} to read and write to your target database.

. xref:astra-db-serverless:databases:secure-connect-bundle.adoc[Download your database's {scb}].
The {scb-short} is a zip file that contains TLS encryption certificates and other metadata required to connect to your database.
+
[IMPORTANT]
====
The {scb-short} contains sensitive information that establishes a connection to your database, including key pairs and certificates.
Treat it as you would any other sensitive values, such as passwords or tokens.
====
+
Your client application uses the {scb-short} to connect directly to {astra-db} near the end of the migration, and {cass-migrator} and {dsbulk-migrator} use the {scb-short} to migrate and validate data in {astra-db}.

. Use `scp` to copy the {scb-short} to your client application instance:
+
[source,bash]
----
scp -i <your_ssh_key> /path/to/scb.zip <linux user>@<public IP of client application instance>:
----

. Recreate your client application's schema on your {astra-db} database, including each keyspace and table that you want to migrate.
+
[IMPORTANT]
====
On your new database, the keyspace names, table names, column names, data types, and primary keys must be identical to the schema on the origin cluster or the migration will fail.
====
+
Note the following limitations and exceptions for tables in {astra-db}:
+
* In {astra-db}, you must create keyspaces in the {astra-ui} or with the {devops-api} because xref:astra-db-serverless:cql:develop-with-cql.adoc[CQL for {astra-db}] doesn't support `CREATE KEYSPACE`.
For instructions, see xref:astra-db-serverless:databases:manage-keyspaces.adoc[].
* You can use {astra-db}'s built-in or standalone `cqlsh` to issue typical CQL statements to xref:astra-db-serverless:databases:manage-collections.adoc#create-a-table[create tables in {astra-db}].
However, the only optional table properties that {astra-db} supports are `default_time_to_live` and `comment`.
As a best practice, omit unsupported table properties, such as compaction strategy and `gc_grace_seconds`, when creating tables in {astra-db} because xref:astra-db-serverless:cql:develop-with-cql.adoc#unsupported-values-are-ignored[CQL for {astra-db} ignores all unsupported values].
* {astra-db} doesn't support Materialized Views (MVs) and certain types of indexes.
You must replace these with supported indexes.
For more information, see xref:astra-db-serverless:cql:develop-with-cql.adoc#limitations-on-cql-for-astra-db[Limitations on CQL for {astra-db}].
+
To help you prepare the schema from the DDL in your origin cluster, consider using the `generate-ddl` functionality in the {dsbulk-migrator-repo}[{dsbulk-migrator}].
However, this tool doesn't automatically convert MVs or indexes.
--

Use a generic CQL cluster as the target::
+
--
{product-short} can be used to migrate to any type of CQL cluster, running in any cloud or on-premise.

To migrate data to any other generic CQL cluster, such as {hcd-short} or OSS {cass-short}, do the following:

. Provision infrastructure, and then create the new cluster with your desired database platform version and configuration:
+
.. Determine the correct topology and specifications for your new cluster, and then provision infrastructure that meets those requirements.
Your target infrastructure can be hosted on a cloud provider, in a private cloud, or on bare metal machines.
.. Create your cluster using your desired CQL cluster version.
For specific infrastructure, installation, and configuration instructions, see the documentation for your infrastructure platform, database platform, and database platform version.
Pay particular attention at configuration that must be done at installation time.
.. Configure your new cluster as desired.
+
[TIP]
====
Because {product-proxy} supports separate connection details for each cluster, your new cluster can be configured as you wish, independent of the origin cluster's configuration.

This is a good opportunity to establish your desired configuration state on the new cluster and implement new patterns that might have been unavailable or impractical on the old cluster, such as enabling authentication or configuring TLS encryption.
====
.. Recommended: Consider testing your new cluster to ensure it meets your performance requirements, and then tune it as necessary before beginning the migration.

. If you enabled authentication, create a user with the required permissions for your client application to use to read and write to the cluster.

. Recreate your client application's schema on your new cluster, including each keyspace and table that you want to migrate.
+
[IMPORTANT]
====
On your new cluster, the keyspace names, table names, column names, data types, and primary keys must be identical to the schema on the origin cluster or the migration will fail.
====
+
To copy the schema, you can run CQL `describe` on the origin cluster to get the schema that is being migrated, and then run the output on your new cluster.
+
If you are migrating from an old version, you might need to edit CQL clauses that are no longer supported in newer versions, such as `COMPACT STORAGE`.
For specific changes in each version, see your driver's changelog or release notes.
--
======

== Next steps

* xref:ROOT:rollback.adoc[]