= Create the target environment for your migration
:navtitle: Create target environment for migration
:page-tag: migration,zdm,zero-downtime,zdm-proxy,target
ifdef::env-github,env-browser,env-vscode[:imagesprefix: ../images/]
ifndef::env-github,env-browser,env-vscode[:imagesprefix: ]

In this topic, we'll see how to create and prepare a new cluster to be used as Target.

This section covers in detail the steps to prepare an {astra-db} Serverless database, and also outlines how to create and prepare a different cluster, which could be for example {cass-short} 4.0.x or {dse-short} 6.8.x.

== Overview

If you intend to use {astra-db} as Target for the migration, you will need to:

* Create an {astra-db} Serverless database.
* Retrieve its Secure Connect Bundle (SCB) and upload it to the application instances.
* Create {astra-db} access credentials for your database.
* Create the client application schema.

To use a generic {cass-short} or {dse-short} cluster, you will have to:

* Provision the infrastructure for your new cluster.
* Create the cluster with the desired version of {cass-short} or {dse-short}.
* Configure the cluster according to your requirements.
* Create the client application schema.

== Using an {astra-db} database as Target

=== Prerequisites

* An active {astra-url}[{astra-db} account^]

=== Create an {astra-db} Serverless database

Log into the {astra-ui} and create an {astra-db} Serverless database.
You can start with a Free plan, but consider upgrading during your migration project to an {astra-db} Pay As You Go or Enterprise plan, to take advantage of additional functionality -- such as Exporting Metrics to external third-party applications, Bring Your Own Keys, and other features.

The Pay As You Go and Enterprise plans have many benefits over the Free plan, such as the ability to lift rate limiting, and avoiding hibernation timeouts.

Assign your preferred values for the serverless database:

* **Name**.
* **Keyspace**: this is a handle that establishes the database's context in subsequent DDL and DML statements.
* **Cloud provider**: You can choose your preferred cloud provider among AWS, GCP and Azure (only GCP is available to Free Tier accounts).
* **Region**: choose your geographically preferred region - you can subsequently add more regions.

When the {astra-db} database reaches **Active** status, create an application token in the {astra-ui} with the *Read/Write User* role.
This role will be used by the client application, the {product-proxy}, and the {product-automation}.

Save the generate token and credentials (Client ID, Client Secret, and Token) in a clearly-named secure file.

=== Get the Secure Connect Bundle and upload to client instances

Your database's https://docs.datastax.com/en/astra/astra-db-vector/drivers/secure-connect-bundle.html#download-the-secure-connect-bundle[Secure Connect Bundle] (SCB) is a zip file that contains the TLS encryption certificates and other metadata to connect to your database.
It will be needed by:

* Your client application, to connect directly to {astra-db} near the end of the migration;
* {cass-migrator} or {dsbulk-migrator}, to migrate and validate data into {astra-db}.

Note that the credentials are **not contained** in the SCB.

// * The {company} Bulk Migrator to import the existing data into {astra-db}

include::partial$tip-scb.adoc[]

To copy the SCB to your client application instance, use `scp`:

[source,bash]
----
scp -i <your_ssh_key> secure-connect-<target cluster name>.zip <linux user>@<public IP of client application instance>:
----

=== Create the client application schema on your {astra-db} database

To complete the preparation work, create the client application schema in your newly created {astra-db} database.

In the {astra-ui}, create each corresponding keyspace and table.
The keyspace names, table names and structure must be identical to the schema on Origin, bearing in mind that:

* In {astra-db}, keyspaces must be created in the {astra-ui}.
Keyspace creation through CQL is not supported.
See https://docs.datastax.com/en/astra/astra-db-vector/databases/create-database.html[create your database], and https://docs.datastax.com/en/astra/astra-db-vector/databases/manage-keyspaces.html#add-keyspace[adding a new keyspace].

* Tables can be defined as usual in regular CQL, but the only table property that can be optionally set in {astra-db} is `default_time_to_live`.
Please remove all other table properties (such as compaction strategy, `gc_grace_seconds` and so on).

* Materialized Views (MVs) and certain types of indexes are not supported in {astra-db}, and should be replaced with supported indexes. See https://docs.datastax.com/en/astra/astra-db-vector/databases/database-limits.html#fields[Serverless database limits] for more details.

To aid you in preparing the schema from the DDL used in a {cass} or {dse-short} cluster, you may wish to consider the `generate-ddl` functionality in the link:https://github.com/datastax/dsbulk-migrator[{dsbulk-migrator}]. Note that Materialized Views and indexes are not automatically converted by this tool.

Note that CQL statements, such as those used to reproduce the schema on the target database, can be executed in {astra-db} using two methods:

. A CQL Console located directly https://docs.datastax.com/en/astra/astra-db-vector/cql/connect-cql-shell.html#embedded-cql-shell[in the {astra-ui}].
. Any machine connected remotely using an {astra-db}-compatible https://docs.datastax.com/en/astra/astra-db-vector/cql/connect-cql-shell.html#standalone-cql-shell[standalone `cqlsh` client] (and provide the necessary connection secrets).

== Using a generic CQL cluster as Target

=== Create and configure the cluster

{product-short} can be used to migrate to any type of CQL cluster, running in any cloud or even on-premise.

Here are the steps that you'll need to follow:

* Determine the correct topology and specifications for your new cluster, then provision infrastructure that meets these requirements.
This can be in your cloud provider of choice, in your own private cloud or on bare metal machines.
* Create your cluster using your chosen version of {cass-short} or {dse-short}.
Refer to the documentation specific to the version that you are installing for detailed information, and pay particular attention at configuration that must be done at installation time.
* Configure your new cluster as desired: for example, you may decide to enable internal authentication or configure TLS encryption.
You should also consider testing your new cluster to ensure it meets your performance requirements and tune it as necessary.
+
[NOTE]
====
Your new cluster can be configured as you wish, independently of how Origin is configured.
{product-proxy} allows you to specify a separate set of configuration to connect to each cluster.
====

* If you enabled authentication, create a user with the required permissions to be used for your client application.

=== Create the client application schema on the cluster

At this point, the only thing that is left to do is creating the schema for your client application on the new cluster.

[IMPORTANT]
====
Make sure that all keyspaces and tables being migrated are identical to the corresponding ones on Origin (including keyspace, table and column names).
====

* To copy the schema, you can simply run CQL `describe` on Origin for the schema that is being migrated, and then run the output on your new cluster.
Bear in mind that, if you are migrating from an old version, you may need to adapt some CQL clauses that are no longer supported in newer versions (e.g. `COMPACT STORAGE`).
Please refer to the documentation of the relevant versions for more information.