= Use {dsbulk-migrator} with {product-proxy}
:navtitle: Use {dsbulk-migrator}
:description: {dsbulk-migrator} extends {dsbulk-loader} with migration commands.
:page-aliases: ROOT:dsbulk-migrator-overview.adoc

{dsbulk-migrator} is an extension of xref:dsbulk:overview:dsbulk-about.adoc[{dsbulk-loader}] that adds the following three commands:

* `migrate-live`: Immediately runs a live data migration using {dsbulk-loader}.

* `generate-script`: Generates a migration script that you can use to run a data migration with a standalone {dsbulk-loader} installation.
This command _doesn't_ trigger the migration; it only generates the migration script.

* `generate-ddl`: Reads the origin cluster's schema, and then generates CQL files that you can use to recreate the schema on your target cluster in preparation for data migration.

{dsbulk-migrator} is best for smaller migrations and migrations that don't require extensive data validation aside from post-migration row counts.
You might also use this tool for migrations where you can shard data from large tables into more manageable quantities.

You can use {dsbulk-migrator} alone or with {product-proxy}.

== Install {dsbulk-migrator}

. Install Java 11 and https://maven.apache.org/download.cgi[Maven] 3.9.x.

. Optional: If you don't want to use the embedded {dsbulk-loader} that is bundled with {dsbulk-migrator}, you must xref:dsbulk:overview:install.adoc[install {dsbulk-loader}] before installing {dsbulk-migrator}.

. Clone the {dsbulk-migrator-repo}[{dsbulk-migrator} repository]:
+
[source,bash]
----
git clone git@github.com:datastax/dsbulk-migrator.git
----

. Change to the cloned directory:
+
[source,bash]
----
cd dsbulk-migrator
----

. Use Maven to build {dsbulk-migrator}:
+
[source,bash]
----
mvn clean package
----
+
[[dsbulk-jar]]The build produces two distributable fat jars.
You will use one of these jars when you run a {dsbulk-migrator} command.
+
* `dsbulk-migrator-**VERSION**-embedded-dsbulk.jar`: Contains an embedded {dsbulk-loader} installation and an embedded Java driver.
+
Supports all {dsbulk-migrator} operations, but it is larger than the other JAR due to the presence of the {dsbulk-loader} classes.
+
Use this jar if you _don't_ want to use your own {dsbulk-loader} installation.

* `dsbulk-migrator-**VERSION**-embedded-driver.jar`: Contains an embedded Java driver only.
+
Suitable for using the `generate-script` and `migrate-live` commands with your own {dsbulk-loader} installation.
+
You cannot use this jar for `migrate-live` with the embedded {dsbulk-loader} because the required {dsbulk-loader} classes aren't present in this jar.

. https://github.com/datastax/simulacron[Clone and build Simulacron], which is required for some {dsbulk-migrator} integration tests.
+
Note the https://github.com/datastax/simulacron?tab=readme-ov-file#prerequisites[prerequisites for Simulacron], particularly for macOS.

. Run the {dsbulk-migrator} integration tests:
+
[source,bash]
----
mvn clean verify
----

After you install, build, and test {dsbulk-migrator}, you can run it from the command line, specifying your desired jar, command, and options.

For a quick test, try the `<<get-help-for-dsbulk-migrator,--help>>` option.

For information and examples for each command, see the following:

* <<dsbulk-live>>
* <<dsbulk-script>>
* <<dsbulk-ddl>>

[#get-help-for-dsbulk-migrator]
== Get help for {dsbulk-migrator}

Use `--help` (`-h`) to get information about {dsbulk-migrator} commands and options:

* Print the available {dsbulk-migrator} commands:
+
[source,bash]
----
java -jar /path/to/dsbulk-migrator.jar --help
----
+
Replace `/path/to/dsbulk-migrator.jar` with the path to your <<dsbulk-jar,{dsbulk-migrator} fat jar>>.

* Print help for a specific command:
+
[source,bash,subs="+quotes"]
----
java -jar /path/to/dsbulk-migrator.jar **COMMAND** --help
----
+
Replace the following:
+
** `/path/to/dsbulk-migrator.jar`: The path to your <<dsbulk-jar,{dsbulk-migrator} fat jar>>.
** `COMMAND`: The command for which you want to get help, one of `migrate-live`, `generate-script`, or `generate-ddl`.

[#dsbulk-live]
== Run a live migration

The `migrate-live` command immediately runs a live data migration using the embedded version of {dsbulk-loader} or your own {dsbulk-loader} installation.
A _live migration_ means the data migration starts immediately, and it is handled by the migrator tool through the specified {dsbulk-loader} installation.

To run the `migrate-live` command, provide the path to your <<dsbulk-jar,{dsbulk-migrator} fat jar>> followed by `migrate-live` and any options:

[source,bash,subs="+quotes"]
----
java -jar /path/to/dsbulk-migrator.jar migrate-live **OPTIONS**
----

The following examples show how to use either fat jar to perform a live migration where the target cluster is an {astra-db} database.
The password parameters are left blank so that {dsbulk-migrator} prompts for them interactively during the migration.
All unspecified options use their default values.

[tabs]
======
Use the embedded {dsbulk-loader}::
+
--
If you want to run the migration with the embedded {dsbulk-loader}, you must use the `dsbulk-migrator-**VERSION**-embedded-dsbulk.jar` fat jar and the `--dsbulk-use-embedded` option:

[source,bash,subs="+quotes"]
----
    java -jar target/dsbulk-migrator-**VERSION**-embedded-dsbulk.jar migrate-live \
        --data-dir=/path/to/data/dir \
        --dsbulk-use-embedded \
        --dsbulk-log-dir=/path/to/log/dir \
        --export-host=**ORIGIN_CLUSTER_HOSTNAME** \
        --export-username=**ORIGIN_USERNAME** \
        --export-password # Origin password will be prompted \
        --export-dsbulk-option "--connector.csv.maxCharsPerColumn=65536" \
        --export-dsbulk-option "--executor.maxPerSecond=1000" \
        --import-bundle=/path/to/scb.zip \
        --import-username=token \
        --import-password # Application token will be prompted \
        --import-dsbulk-option "--connector.csv.maxCharsPerColumn=65536" \
        --import-dsbulk-option "--executor.maxPerSecond=1000"
----
--

Use your own {dsbulk-loader} installation::
+
--
If you want to run the migration with your own {dsbulk-loader} installation, use the `dsbulk-migrator-**VERSION**-embedded-driver.jar` fat jar, and use the `--dsbulk-cmd` option to specify the path to your {dsbulk-loader} installation:

[source,bash,subs="+quotes,macros"]
----
    java -jar target/dsbulk-migrator-**VERSION**-embedded-driver.jar migrate-live \
        --data-dir=/path/to/data/dir \
        --dsbulk-cmd=pass:q[${DSBULK_ROOT}]/bin/dsbulk \
        --dsbulk-log-dir=/path/to/log/dir \
        --export-host=**ORIGIN_CLUSTER_HOSTNAME** \
        --export-username=**ORIGIN_USERNAME** \
        --export-password # Origin password will be prompted \
        --import-bundle=/path/to/scb.zip \
        --import-username=token \
        --import-password # Application token will be prompted
----

--
======

=== Options for migrate-live

Options for the `migrate-live` command are used to configure the migration parameters and connect to the origin and target clusters.

Most options have sensible default values and don't need to be specified unless you want to override the default value.

[cols="1,3"]
|===
| Option | Description

| `--data-dir=PATH` (`-d`)
| The directory where data will be exported to and imported from.
The default is a `data` subdirectory in the current working directory.
The data directory will be created if it does not exist.
Tables will be exported and imported in subdirectories of the data directory specified here.
There will be one subdirectory per keyspace in the data directory, then one subdirectory per table in each keyspace directory.

| `--dsbulk-cmd` (`-c`)
| The path to your own external (non-embedded) {dsbulk-loader} installation, such as `--dsbulk-cmd=pass:q[${DSBULK_ROOT}]/bin/dsbulk`.

The default is `dsbulk`, which assumes that the command is available through the `PATH` variable contents.

Ignored if the embedded {dsbulk-loader} is used (`--dsbulk-use-embedded`).

| `--dsbulk-use-embedded` (`-e`)
| Use the embedded {dsbulk-loader}.
Accepts no arguments; it's either included (enabled) or not (disabled).

By default, this option is disabled/omitted, and `migrate-live` expects to use an external (non-embedded) {dsbulk-loader} installation.
If disabled/omitted, set the path to your {dsbulk-loader} installation in `--dsbulk-cmd`.

| `--export-bundle`
| If your origin cluster is an {astra-db} database, provide the path to your database's {scb}, such as `--export-bundle=/path/to/scb.zip`.

Cannot be used with `--export-host`.

| `--export-consistency`
| The consistency level to use when exporting data.
The default is `--export-consistency=LOCAL_QUORUM`.

| `--export-dsbulk-option`
| An additional xref:dsbulk:reference:dsbulk-cmd.adoc#options[{dsbulk-loader} option] to use when exporting data.

The expected format is `--export-dsbulk-option "--option.full.name=value"`.

You must use the option's full long form name and leading dashes; short form options will fail.
You must wrap the entire expression in quotes so that it is handled correctly by {dsbulk-migrator}.
This is in addition to any xref:dsbulk:reference:dsbulk-cmd.adoc#escape-and-quote-command-line-arguments[escaping] required for {dsbulk-loader} to process the option correctly.

To pass multiple additional options, pass each option separately with `--export-dsbulk-option`.
For example: `--export-dsbulk-option "--connector.csv.maxCharsPerColumn=65536" --export-dsbulk-option "--executor.maxPerSecond=1000"`.

| `--export-host`
a| The origin cluster's host name or IP address, and an optional port for a node in the origin cluster.
The default port is `9042` if not specified.
For example:

* Hostname with default port: `--export-host=db2.example.com`
* Hostname with custom port: `--export-host=db1.example.com:9001`
* IP address with default port: `--export-host=1.2.3.5`
* IP address with custom port: `--export-host=1.2.3.4:9001`

This option can be passed multiple times.

If your origin cluster is an {astra-db} database, use `--export-bundle` instead of `--export-host`.

| `--export-max-concurrent-files`
| The maximum number of concurrent files to write to when exporting data from the origin cluster.

Can be either `AUTO` (default) or a positive integer, such as `--export-max-concurrent-files=8`.

| `--export-max-concurrent-queries`
| The maximum number of concurrent queries to execute.

Can be either `AUTO` (default) or a positive integer, such as `--export-max-concurrent-queries=8`.

| `--export-max-records`
| The maximum number of records to export for each table.

The default is `-1`, which exports the entire table (all records).

To export a fixed number of records, set to a positive integer, such as `--export-max-records=10000`.

| `--export-password`
| The password for authentication to the origin cluster.

You can either provide the password directly (`--export-password=pass:q[${ORIGIN_PASSWORD}]`), or pass the option without a value (`--export-password`) to be prompted for the password interactively.

If set, then `--export-username` is required.

If the cluster doesn't require authentication, omit both `--export-username` and `--export-password`.

If your origin cluster is an {astra-db} database, the password is an {astra} application token.

| `--export-splits`
a| The maximum number of token range queries to generate.

This is an advanced setting that {company} doesn't recommend modifying unless you have a specific need to do so.

Can be either of the following:

* A positive integer, such as `--export-splits=16`.
* A multiple of the number of available cores, specified as `NC` where `N` is the number of cores, such as `--export-splits=8C`.

The default is `8C` (8 times the number of available cores).

| `--export-username`
| The username for authentication to the origin cluster.

If set, then `--export-password` is required.

If the cluster doesn't require authentication, omit both `--export-username` and `--export-password`.

If your origin cluster is an {astra-db} database, the username is the literal string `token`, such as `--export-username=token`.

| `--import-bundle`
| If your target cluster is an {astra-db} database, provide the path to your database's {scb}, such as `--import-bundle=/path/to/scb.zip`.

Cannot be used with `--import-host`.

| `--import-consistency`
| The consistency level to use when importing data.
The default is `--import-consistency=LOCAL_QUORUM`.

| `--import-default-timestamp`
| The default timestamp to use when importing data.
Must be a valid instant in ISO-8601 format.
The default is `--import-default-timestamp=1970-01-01T00:00:00Z`.

| `--import-dsbulk-option`
| An additional xref:dsbulk:reference:dsbulk-cmd.adoc#options[{dsbulk-loader} option] to use when importing data.

The expected format is `--import-dsbulk-option "--option.full.name=value"`.

You must use the option's full long form name and leading dashes; short form options will fail.
You must wrap the entire expression in quotes so that it is handled correctly by {dsbulk-migrator}.
This is in addition to any xref:dsbulk:reference:dsbulk-cmd.adoc#escape-and-quote-command-line-arguments[escaping] required for {dsbulk-loader} to process the option correctly.

To pass multiple additional options, pass each option separately with `--import-dsbulk-option`.
For example: `--import-dsbulk-option "--connector.csv.maxCharsPerColumn=65536" --import-dsbulk-option "--executor.maxPerSecond=1000"`.

| `--import-host`
a| The target cluster's host name or IP address, and an optional port for a node in the target cluster.
The default port is `9042` if not specified.
For example:

* Hostname with default port: `--import-host=db2.example.com`
* Hostname with custom port: `--import-host=db1.example.com:9001`
* IP address with default port: `--import-host=1.2.3.5`
* IP address with custom port: `--import-host=1.2.3.4:9001`

This option can be passed multiple times.

If your target cluster is an {astra-db} database, use `--import-bundle` instead of `--import-host`.

| `--import-max-concurrent-files`
| The maximum number of concurrent files to read from when importing data to the target cluster.

Can be either `AUTO` (default) or a positive integer, such as `--import-max-concurrent-files=8`.

| `--import-max-concurrent-queries`
| The maximum number of concurrent queries to execute.

Can be either `AUTO` (default) or a positive integer, such as `--import-max-concurrent-queries=8`.

| `--import-max-errors`
| The maximum number of failed records to tolerate when importing data.

Must be a positive integer, such as `--import-max-errors=5000`.
The default is `1000`.

Failed records are written to a `load.bad` file in the {dsbulk-loader} operation directory.

| `--import-password`
| The password for authentication to the target cluster.

You can either provide the password directly (`--import-password=pass:q[${TARGET_PASSWORD}]`), or pass the option without a value (`--import-password`) to be prompted for the password interactively.

If set, then `--import-username` is required.

If the cluster doesn't require authentication, omit both `--import-username` and `--import-password`.

If your target cluster is an {astra-db} database, the password is an {astra} application token.

| `--import-username`
| The username for authentication to the target cluster.

If set, then `--import-password` is required.

If the cluster doesn't require authentication, omit both `--import-username` and `--import-password`.

If your target cluster is an {astra-db} database, the username is the literal string `token`, such as `--import-username=token`.

| `--keyspaces` (`-k`)
| A regular expression to select keyspaces to migrate, such as `--keyspaces="^(my_keyspace\|anotherKeyspace)$"`.

The default behavior is to migrate all keyspaces except system keyspaces, {dse-short}-specific keyspaces, and the OpsCenter keyspace if these are present on the origin cluster.

Case-sensitive keyspace names must be specified by their exact case.

| `--dsbulk-log-dir` (`-l`)
| The path to the directory where you want to store {dsbulk-loader} logs, such as `--dsbulk-log-dir=~/tmp/dsbulk-logs`.
The default is a `logs` subdirectory in the current working directory.
This subdirectory is created if it doesn't exist.

Each {dsbulk-loader} operation creates its own subdirectory within the specified log directory.

| `--max-concurrent-ops`
| The maximum number of concurrent operations (exports and imports) to execute at any given time.

The default is `1`.

Increase this value to allow exports and imports to occur concurrently.
For example, if `--max-concurrent-ops=2`, then each table is imported as soon as it is exported, and the next table immediately begins being exported as soon as the previous table starts importing.

| `--skip-truncate-confirmation`
| Whether to bypass truncate confirmation before actually truncating tables.

The default is disabled/omitted, which means you must confirm truncation before tables are truncated.

Only applicable when migrating counter tables.
This option is ignored otherwise.

| `--tables` (`-t`)
| A regular expression to select tables to migrate, such as `--tables="^(table1\|table_two)$"`.

The default behavior is to migrate all tables in the keyspaces that are selected by the `--keyspaces` option.

Case-sensitive table names must be specified by their exact case.

| `--table-types`
a| The table types to migrate:

* `--table-types=regular`: Migrate only regular tables.
* `--table-types=counter`: Migrate only counter tables.
* `--table-types=all` (default): Migrate both regular and counter tables.

| `--truncate-before-export`
| Truncate tables before export them instead of truncating them afterwards.

The default is disabled/omitted, which means tables are truncated after being exported.

Only applicable when migrating counter tables.
This option is ignored otherwise.

| `--dsbulk-working-dir` (`-w`)
| The path to the directory where you want to run `dsbulk`, such as `--dsbulk-working-dir=~/tmp/dsbulk-work`.
The default is the current working directory.

Only applicable when using your own external (non-embedded) {dsbulk-loader} installation with the `--dsbulk-cmd` option.
Ignored if the embedded {dsbulk-loader} is used (`--dsbulk-use-embedded`).
|===

[#dsbulk-script]
== Generate a migration script

The `generate-script` command generates a migration script that you can use to perform a data migration with your own {dsbulk-loader} installation.
This command _doesn't_ trigger the migration; it only generates the migration script that you must then run.

If you want to run a migration immediately, or you want to use the embedded {dsbulk-loader}, use the `migrate-live` command instead.

To run the `generate-script` command, provide the path to your <<dsbulk-jar,{dsbulk-migrator} fat jar>> followed by `generate-script` and any options:

[source,bash,subs="+quotes"]
----
java -jar /path/to/dsbulk-migrator.jar generate-script **OPTIONS**
----

The following example generates a migration script where the target cluster is an {astra-db} database.
The `--dsbulk-cmd` option specifies the path to the {dsbulk-loader} installation that you plan to use to run the generated migration script.
All unspecified options use their default values.

[source,bash,subs="+quotes,macros"]
----
    java -jar target/dsbulk-migrator-**VERSION**-embedded-driver.jar generate-script \
        --data-dir=/path/to/data/dir \
        --dsbulk-cmd=pass:q[${DSBULK_ROOT}]/bin/dsbulk \
        --dsbulk-log-dir=/path/to/log/dir \
        --export-host=**ORIGIN_CLUSTER_HOSTNAME** \
        --export-username=**ORIGIN_USERNAME** \
        --export-password=**ORIGIN_PASSWORD** \
        --import-bundle=/path/to/scb.zip \
        --import-username=token \
        --import-password=**ASTRA_APPLICATION_TOKEN**
----

=== Options for generate-script

When generating a migration script, most options become default values in the generated scripts.
However, {dsbulk-migrator} needs to access the origin cluster to gather metadata about the tables to migrate.

The following options are available for the `generate-script` command.
Most options have sensible default values and don't need to be specified unless you want to override the default value.

[cols="1,3"]
|===
| Option | Description

| `--dsbulk-cmd=CMD` (`-c`)
| The {dsbulk-loader} command to use.
The default is simply `dsbulk`, assuming that the command is available through the `PATH` variable contents.

| `--data-dir=PATH` (`-d`)
| The directory where data will be exported to and imported from. 
The default is a `data` subdirectory in the current working directory. 
The data directory will be created if it does not exist. 

| `--export-bundle=PATH`
| The path to a secure connect bundle to connect to the origin cluster, if that cluster is a {company} {astra-db} cluster.
Options `--export-host` and `--export-bundle` are mutually exclusive.

| `--export-consistency=CONSISTENCY`
| The consistency level to use when exporting data.
The default is `LOCAL_QUORUM`.

| `--export-dsbulk-option=OPT=VALUE`
| An extra {dsbulk-loader} option to use when exporting.
Any valid {dsbulk-loader} option can be specified here, and it will passed as is to the {dsbulk-loader} process.
{dsbulk-loader} options, including driver options, must be passed as `--long.option.name=<value>`.
Short options are not supported.

| `--export-host=HOST[:PORT]`
| The host name or IP and, optionally, the port of a node from the origin cluster.
If the port is not specified, it will default to `9042`.
This option can be specified multiple times.
Options `--export-host` and `--export-bundle` are mutually exclusive.

| `--export-max-concurrent-files=NUM\|AUTO`
| The maximum number of concurrent files to write to.
Must be a positive number or the special value `AUTO`.
The default is `AUTO`.

| `--export-max-concurrent-queries=NUM\|AUTO`
| The maximum number of concurrent queries to execute.
Must be a positive number or the special value `AUTO`.
The default is `AUTO`.

| `--export-max-records=NUM`
| The maximum number of records to export for each table.
Must be a positive number or `-1`.
The default is `-1` (export the entire table).

| `--export-password`
| The password to use to authenticate against the origin cluster.
Options `--export-username` and `--export-password` must be provided together, or not at all.
Omit the parameter value to be prompted for the password interactively.

| `--export-splits=NUM\|NC`
| The maximum number of token range queries to generate.
Use the `NC` syntax to specify a multiple of the number of available cores.
For example, `8C` = 8 times the number of available cores.
The default is `8C`.
This is an advanced setting.
You should rarely need to modify the default value.

| `--export-username=STRING`
| The username to use to authenticate against the origin cluster.
Options `--export-username` and `--export-password` must be provided together, or not at all.

| `--import-bundle=PATH`
| The path to a Secure Connect Bundle to connect to a target {astra-db} cluster.
Options `--import-host` and `--import-bundle` are mutually exclusive.

| `--import-consistency=CONSISTENCY`
| The consistency level to use when importing data.
The default is `LOCAL_QUORUM`.

| `--import-default-timestamp=<defaultTimestamp>`
| The default timestamp to use when importing data.
Must be a valid instant in ISO-8601 syntax.
The default is `1970-01-01T00:00:00Z`.

| `--import-dsbulk-option=OPT=VALUE`
| An extra {dsbulk-loader} option to use when importing.
Any valid {dsbulk-loader} option can be specified here, and it will passed as is to the {dsbulk-loader} process.
{dsbulk-loader} options, including driver options, must be passed as `--long.option.name=<value>`.
Short options are not supported.

| `--import-host=HOST[:PORT]`
| The host name or IP and, optionally, the port of a node on the target cluster.
If the port is not specified, it will default to `9042`.
This option can be specified multiple times.
Options `--import-host` and `--import-bundle` are mutually exclusive.

| `--import-max-concurrent-files=NUM\|AUTO`
| The maximum number of concurrent files to read from.
Must be a positive number or the special value `AUTO`.
The default is `AUTO`.

| `--import-max-concurrent-queries=NUM\|AUTO`
| The maximum number of concurrent queries to execute.
Must be a positive number or the special value `AUTO`.
The default is `AUTO`.

| `--import-max-errors=NUM`
| The maximum number of failed records to tolerate when importing data.
The default is `1000`.
Failed records will appear in a `load.bad` file in the {dsbulk-loader} operation directory.

| `--import-password`
| The password to use to authenticate against the target cluster.
Options `--import-username` and `--import-password` must be provided together, or not at all.
Omit the parameter value to be prompted for the password interactively.

| `--import-username=STRING`
| The username to use to authenticate against the target cluster.
Options `--import-username` and `--import-password` must be provided together, or not at all.

| `--keyspaces=REGEX` (`-k`)
| A regular expression to select keyspaces to migrate.
The default is to migrate all keyspaces except system keyspaces, {dse-short}-specific keyspaces, and the OpsCenter keyspace.
Case-sensitive keyspace names must be entered in their exact case.

| `--dsbulk-log-dir=PATH` (`-l`)
| The directory where {dsbulk-loader} should store its logs.
The default is a `logs` subdirectory in the current working directory.
This subdirectory will be created if it does not exist.
Each {dsbulk-loader} operation will create a subdirectory in the log directory specified here.

| `--tables=REGEX` (`-t`)
| A regular expression to select tables to migrate.
The default is to migrate all tables in the keyspaces that were selected for migration with `--keyspaces`.
Case-sensitive table names must be entered in their exact case.

| `--table-types=regular\|counter\|all`
| The table types to migrate. The default is `all`.

|===

[#dsbulk-ddl]
== Generate DDL files

The `generate-ddl` command reads the origin cluster's schema, and then generates CQL files that you can use to recreate the schema on your target CQL-compatible cluster.

To run the `generate-ddl` command, provide the path to your <<dsbulk-jar,{dsbulk-migrator} fat jar>> followed by `generate-ddl` and any options:

[source,bash,subs="+quotes"]
----
java -jar /path/to/dsbulk-migrator.jar generate-ddl **OPTIONS**
----

The following example generates DDL files that are optimized for recreating the schema on an {astra-db} database:

[source,bash,subs="+quotes"]
----
    java -jar target/dsbulk-migrator-**VERSION**-embedded-driver.jar generate-ddl \
        --data-dir=/path/to/data/directory \
        --export-host=**ORIGIN_CLUSTER_HOSTNAME** \
        --export-username=**ORIGIN_USERNAME** \
        --export-password=**ORIGIN_PASSWORD** \
        --optimize-for-astra
----

=== Options for generate-ddl

The `generate-ddl` command ignores all `import-{asterisk}` options and {dsbulk-loader}-related options because they aren't relevant to this operation.

Origin cluster connection details (`export-{asterisk}` options) are required so that {dsbulk-migrator} can access the origin cluster to gather metadata about the keyspaces and tables for the DDL statements.

Most options have sensible default values and don't need to be specified unless you want to override the default value.

[cols="1,3"]
|===
| Option | Description

| `--optimize-for-astra` (`-a`)
| Produce CQL scripts optimized for {company} {astra-db}.
{astra-db} does not allow some options in DDL statements.
Using this {dsbulk-migrator} command option, forbidden {astra-db} options will be omitted from the generated CQL files.

| `--data-dir=PATH` (`-d`)
| The directory where data will be exported to and imported from.
The default is a `data` subdirectory in the current working directory.
The data directory will be created if it does not exist.

| `--export-bundle=PATH`
| The path to a secure connect bundle to connect to the origin cluster, if that cluster is a {company} {astra-db} cluster.
Options `--export-host` and `--export-bundle` are mutually exclusive.

| `--export-host=HOST[:PORT]`
| The host name or IP and, optionally, the port of a node from the origin cluster.
If the port is not specified, it will default to `9042`.
This option can be specified multiple times.
Options `--export-host` and `--export-bundle` are mutually exclusive.

| `--export-password`
| The password to use to authenticate against the origin cluster.
Options `--export-username` and `--export-password` must be provided together, or not at all.
Omit the parameter value to be prompted for the password interactively.

| `--export-username=STRING`
| The username to use to authenticate against the origin cluster.
Options `--export-username` and `--export-password` must be provided together, or not at all.

| `--keyspaces=REGEX` (`-k`)
| A regular expression to select keyspaces to migrate.
The default is to migrate all keyspaces except system keyspaces, {dse-short}-specific keyspaces, and the OpsCenter keyspace.
Case-sensitive keyspace names must be entered in their exact case.

| `--tables=REGEX` (`-t`)
| A regular expression to select tables to migrate.
The default is to migrate all tables in the keyspaces that were selected for migration with `--keyspaces`.
Case-sensitive table names must be entered in their exact case.

| `--table-types=regular\|counter\|all`
| The table types to migrate.
The default is `all`.

|===