= {dse-short} migration toolkit
:description: Learn which migration tools you can use to migrate data to and from {dse-short}.

The {dse} migration toolkit includes the xref:ROOT:components.adoc[{company} migration tools] that you can use to migrate your data across {dse-short} and another {cass-reg}-based database, such as {astra-db} or {hcd-short}.

This documentation doesn't describe _all_ possible migration paths; it focuses on migrations using {company} migration tools like {product-proxy}.

[TIP]
====
Whenever possible, {company} recommends using the {product} ({product-short}) tools when you need to maintain live traffic for your applications while transferring data.
This is most relevant for full-scale platform migrations where you move your data _and_ switch your applications to connect to your new databases.

The {product-short} tools orchestrate and synchronize read/write requests while you use a data migration tool to copy data from one cluster to the other.
Then, you can take as much time as you need to validate the data and simulate production workloads on your new cluster before updating your application code to use the new databases.

For information about clusters that support the {product-short} tools, including supported {dse-short} versions, see xref:ROOT:zdm-proxy-migration-paths.adoc[].
====

== Migrate your data

The tools and process for data migration to or from {dse-short} depends on your {dse-short} version and the other database's platform or version.

[tabs]
======
Migrate data to {dse-short}::
+
--
The following information provides guidance on migrations _to_ {dse-short}, with a focus on data transfer tools:

* xref:6.9@dse:managing:operations/migrate-data.adoc[Migrate to {dse-short} 6.9]
* xref:6.8@dse:managing:operations/migrate-data.adoc[Migrate to {dse-short} 6.8]
* xref:5.1@dse:managing:operations/migrate-data.adoc[Migrate to {dse-short} 5.1]

Generally, {company} recommends migrating to the latest version of {dse-short}, unless you have a specific functional requirement or a compatibility issue that requires migrating to an earlier version.
--

Migrate data from {dse-short}::
+
--
When migrating _from_ {dse-short} to another {cass-short}-based database, follow the migration guidance for your target database to determine cluster compatibility, migration options, and recommendations.
For example, for {astra-db}, see xref:ROOT:astra-migration-paths.adoc[], and for {hcd-short}, see xref:ROOT:hcd-migration-paths.adoc[].

For information about origin and target clusters that are supported by the {product-short} tools, see xref:ROOT:zdm-proxy-migration-paths.adoc[].

If your target database isn't directly compatible with a migration from {dse-short}, you might need to take interim steps to prepare your data for migration, such as upgrading your {dse-short} version, modifying the data in your existing database to be compatible with the target database, or running an extract, transform, load (ETL) pipeline.
--
======

== Migrate your code

In the case of a platform migration where you want to shift your applications to use your new databases, migrate your data first, and then update your client applications to connect exclusively to the new databases.

If you are already using a xref:datastax-drivers:compatibility:driver-matrix.adoc[compatible {cass-short} driver], you can modify the driver connection string to connect to the new databases.
For some migrations, changing the connection string might be the only change you need to make to your code.
However, you might want to update your code to take advantage of features and improvements available in your new database platform or a newer driver version.

For database-specific connection information, see the documentation for your target database and version.

== Get support for your migration

If you have questions about your {dse-short} migration, contact your {company} account representative or {support-url}[IBM Support].

== See also

* xref:ROOT:mc-migration-paths.adoc[]