= Glossary

//TODO: Determine which terms are actually needed. Convert to partials if the definitions need to be repeated, otherwise replace links to this page with links to more useful and complete information.

Here are a few terms used throughout the {company} {product} documentation and code.

[[_ansible_playbooks]]
== Ansible playbooks

A repeatable, re-usable, simple configuration management and multi-machine deployment system, one that is well suited to deploying complex applications.
For details about the playbooks available in {product-automation}, see:

* xref:setup-ansible-playbooks.adoc[].
* xref:deploy-proxy-monitoring.adoc[].

[[_asynchronous_dual_reads]]
== Asynchronous dual reads

An optional feature that is designed to test the target cluster's ability to handle a production workload before you permanently switch to the target cluster at the end of the migration process.

When enabled, {product-proxy} sends asynchronous read requests to the secondary cluster (typically the target cluster) in addition to the synchronous read requests that are sent to the primary cluster by default.

For more information, see xref:ROOT:enable-async-dual-reads.adoc[].

== CQL

{cass-short} Query Language (CQL) is a query language for the {cass-short} database.
It includes DDL and DML statements.
For details, see the xref:cql:ROOT:index.adoc[{cass-short} Query Language documentation].

== Dual-write logic

{product-proxy} handles your client application's real-time write requests and forwards them to two {cass-short}-based origin and target clusters simultaneously.
The dual-write logic in {product-proxy} means that you do not need to modify your client application to perform dual writes manually during a migration: {product-proxy} takes care of it for you.
See the diagram in the xref:introduction.adoc#migration-workflow[workflow introduction].

[[origin]]
== Origin

Your existing {cass-short}-based database that you are migrating away from.
It is the opposite of the <<target>>.

[[_primary_cluster]]
== Primary cluster

The database that is designated as the source of truth for read requests.
It is the opposite of the <<secondary-cluster>>.

The primary cluster is set by {product-automation} through the `primary_cluster` variable, or you can set it directly through the `ZDM_PRIMARY_CLUSTER` environment variable for {product-proxy}.

For the majority of the migration process, the <<origin,origin database>> is typically the primary cluster.
Near the end of the migration, you shift the primary cluster to the <<target,target database>>.

For information about which cluster receives reads and writes during the migration process, see xref:components.adoc#how-zdm-proxy-handles-reads-and-writes[How {product-proxy} handles reads and writes].

== Playbooks

See xref:glossary.adoc#_ansible_playbooks[Ansible playbooks].

== Proxy

Generally speaking, a proxy is a software class functioning as an interface to something else.
The proxy could interface to anything: a network connection, a large object in memory, a file, or some other resource.
A proxy is a wrapper or agent object that is being called by the client to access the real serving object behind the scenes.
In our context here, see <<zdm-proxy,{product-proxy}>>.

== Read mirroring

See <<_asynchronous_dual_reads>>.

[[secondary-cluster]]
== Secondary cluster

The database that isn't designated as the source of truth for read requests.
It is the opposite of the <<_primary_cluster>>.

For the majority of the migration process, the secondary cluster is the <<Target,target database>>.
Near the end of the migration, the target database becomes the <<_primary_cluster>>, and then the <<origin,origin database>> becomes the secondary cluster.

For information about which cluster receives reads and writes during the migration process, see xref:components.adoc#how-zdm-proxy-handles-reads-and-writes[How {product-proxy} handles reads and writes].

[[_secure_connect_bundle_scb]]
== {scb}

A ZIP file that contains connection metadata and TLS encryption certificates (but not the database credentials) for your {astra-db} database.
For more information, see xref:astra-db-serverless:databases:secure-connect-bundle.adoc[].

[[target]]
== Target

The database to which you are migrating your data and applications.
It is the opposite of the <<origin>>.

[[zdm-automation]]
== {product-automation}

An Ansible-based tool that allows you to deploy and manage the {product-proxy} instances and associated monitoring stack.
To simplify its setup, the suite includes {product-utility}.
This interactive utility creates a Docker container acting as the Ansible Control Host.
The Ansible playbooks constitute {product-automation}.

[[zdm-proxy]]
== {product-proxy}

An open-source component designed to seamlessly handle the real-time client application activity while a migration is in progress.
