= Introduction to data migration
:page-tag: migration,zdm,zero-downtime,zdm-proxy, introduction

Enterprises today want to reliably migrate mission-critical client applications and data across environments with little or no downtime during the migration.

{company} has developed a set of thoroughly-tested self-service tools that can help you migrate your data from any {cass-short} origin cluster to any {cass-short}-compatible target.

Compatible origin and target clusters include {cass-reg}, {dse}, {hcd}, and {astra-db}.

When the migration is complete, the data is present in the new database, and you can update your client applications to connect exclusively to the new database.
The old database becomes obsolete and can be removed.

Available migration tools include:

* xref:ROOT:introduction.adoc[{product} ({product-short})]: Comprised of {product-proxy}, {product-utility}, and {product-automation}, you can continue to run your current application and migrate data from the origin to the target database without any downtime.
{product-proxy} helps to manage the activity in transition.
//{product-automation} 2.3.0, which enables ansible scripts and terraform to work with both Ubuntu and RedHat-family Linux distributions.

* xref:ROOT:cassandra-data-migrator.adoc[{cass-migrator}]: You can use {cass-migrator-short} with {product-proxy} for zero-downtime migrations, or you can use {cass-migrator-short} alone for migrations with some downtime.
You can also use {cass-migrator-short} for data validation.

* xref:ROOT:dsbulk-migrator.adoc[{dsbulk-migrator}]: This is an extension of {dsbulk-loader}.
In addition to loading and unloading CSV and JSON data, you can use {dsbulk-migrator} to transfer data between databases.
It can read data from a table from your origin database and write it to a table in your target database.
It can be used as an alternative to {cass-migrator} ({cass-migrator-short}).

* xref:sideloader:sideloader-overview.adoc[{sstable-sideloader}]: {sstable-sideloader} is a service running in {astra-db} that directly imports data from snapshot backups that you've uploaded to {astra-db} from an existing {cass-reg}, {dse}, or {hcd} cluster.