= {company} migration tools
:page-layout: landing

{company} has developed a set of thoroughly tested self-service tools that can help you migrate your data from any origin cluster based on {cass-reg} to any {cass-short}-compatible target with little or no downtime.

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="flex rounded bg-level1 p-6 gap-4">
  <div class="flex flex-col lg:basis-1/2 gap-2">

    <h2 class="discrete !text-h1 !m-0 !mb-4">Secure, reliable migrations</h2>

    <p class="!mb-2">Bulk-load terabytes while shifting traffic with little or no downtime, securely and reliably.</p>

    <div class="flex gap-2 !mt-4">
      xref:ROOT:introduction.adoc[Get started with {product},role="btn btn-primary btn-solid"]
      xref:ROOT:components.adoc[Compare tools,role="btn btn-neutral btn-outlined"]
    </div>

  </div>
  <div class="hidden lg:block flex basis-1/2 relative">
++++

svg::sideloader:astra-migration-toolkit.svg[role="absolute bottom-1/2 translate-y-1/2 right-0 w-full"]

++++
</div>
++++

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++

<h2 class="discrete !text-h1 !mt-12 !mb-6">Migration tools</h2>

<div class="grid gap-6 lg:grid-cols-4">
  <div class="flex flex-col gap-4">

    svg:common:ROOT:icons/datastax/cloud-backup-restore.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">{product-proxy}</h3>

    <p>To support live migrations, {product-proxy} orchestrates activity-in-transition on your clusters, allowing your applications to run while you migrate data.</p>
    <div class="landing-a mt-auto">
        xref:ROOT:introduction.adoc[Get started with {product-short}]
    </div>

  </div>
  <div class="flex flex-col gap-4">

    svg:common:ROOT:icons/datastax/cloud-db.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">{sstable-sideloader}</h3>

    <p>{sstable-sideloader} is a service running in {astra-db} that directly imports data from snapshots of your existing {cass-short}-based cluster.</p>

    <div class="landing-a mt-auto">
        xref:sideloader:sideloader-overview.adoc[Get started with {sstable-sideloader}]
    </div>

  </div>
  <div class="flex flex-col gap-4">

    svg:common:ROOT:icons/datastax/insert-data.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">{cass-migrator} ({cass-migrator-short})</h3>

    <p>{cass-migrator-short} can migrate and validate data between {cass-short}-based clusters, with optional logging and reconciliation support.</p>

    <div class="landing-a mt-auto">
        xref:ROOT:cassandra-data-migrator.adoc[Get started with {cass-migrator-short}]
    </div>

  </div>
  <div class="flex flex-col gap-4">

    svg:common:ROOT:icons/datastax/migrate.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">{dsbulk-loader}</h3>

    <p>{dsbulk-loader} can load, unload, and count large volumes of data from your {cass-short}-based clusters.</p>

    <div class="landing-a mt-auto">
        xref:dsbulk:overview:dsbulk-about.adoc[Get started with {dsbulk-loader}]
    </div>

  </div>
</div>
++++