= Introduction to data migration
:page-tag: migration,zdm,zero-downtime,zdm-proxy,introduction
ifdef::env-github,env-browser,env-vscode[:imagesprefix: ../images/]
ifndef::env-github,env-browser,env-vscode[:imagesprefix: ]

Enterprises today want to reliably migrate mission-critical client applications and data to cloud environments with zero downtime or near zero downtime during the migration. 

{company} has developed a set of thoroughly tested self-service tools to walk you through well-defined migration options.
These tools provide features that help you migrate your data from any Cassandra Origin (Apache Cassandra®, {company} Enterprise (DSE), {company} {astra_db}) to any Cassandra Target (Apache Cassandra®, DSE, {company} {astra_db}).

== Migration process and tools

A migration is a workflow that encompasses the lifecycle of uploading and importing your data to the selected databases. 
{company} can migrate all data, however critical, with acceptable or zero downtime. 
When the migration is complete, the data runs from your cluster to our database.

The migration tools are:

* xref:introduction:adoc[*Zero Downtime Migration*] (ZDM) Proxy: You can continue to run your current application and migrate data to the Origin database without any downtime.
The proxy helps to manage the activity in transition.
* xref:cassandra-data-migrator.adoc[*Cassandra Data Migrator*]: This option for migration with zero downtime when used with the ZDM Proxy, and it can also be used for migrations with acceptable downtime. 
* https://docs.datastax.com/en/dsbulk/overview/dsbulk-about.adoc[*DSBulk Loader*]: Use this option for loading and unloading CSV/JSON data and counting table rows. 
It also allows for migration with zero downtime when used with the ZDM Proxy.
