= Manage your {product-proxy} instances
:page-tag: migration,zdm,zero-downtime,zdm-proxy

In this topic, we'll learn how to perform simple operations on your {product-proxy} deployment with no interruption to its availability:

* Do a simple rolling restart of the {product-proxy} instances
* View or collect the logs of all {product-proxy} instances
* Change a mutable configuration variable
* Upgrade the {product-proxy} version

All these operations can be easily done by running Ansible playbooks.

Make sure you are connected to the Ansible Control Host Docker container. As explained before, you can do so from the jumphost machine by running:

[source,bash]
----
docker exec -it zdm-ansible-container bash
----

You will see a prompt like:

[source,bash]
----
ubuntu@52772568517c:~$
----

== Perform a rolling restart of the proxies

Although this operation is not required in any particular step of the migration, you may still find it convenient in some circumstances. 
For this reason, there is a specific playbook that performs this operation.

Connect to the Ansible Control Host Docker container as explained above and run:

[source,bash]
----
ansible-playbook rolling_restart_zdm_proxy.yml -i zdm_ansible_inventory
----

This is all that is needed.

[NOTE]
====
This playbook simply restarts the existing {product-proxy} containers.
It does **not** apply any configuration change or change the version.

If you wish to xref:change-mutable-config-variable[apply configuration changes] or xref:_upgrade_the_proxy_version[perform version upgrades] in a rolling fashion, follow the instructions in the respective sections.
====

This playbook restarts each proxy container one by one, without impacting the availability of the {product-proxy} deployment. It automates the following steps:

. It stops one container gracefully, waiting for it to shut down.
. It starts the container again.
. It checks that the container has come up successfully by checking the readiness endpoint:
.. If unsuccessful, it repeats the check for six times at 5-second intervals and eventually interrupts the whole process if the check still fails.
.. If successful, it waits for a configurable interval and then moves on to the next container.

The pause between the restart of each {product-proxy} instance defaults to 10 seconds.
To change this value, you can set the desired number of seconds in `zdm-proxy-automation/ansible/vars/zdm_playbook_internal_config.yml`.

[TIP]
====
To check the state of your {product-proxy} instances, you have a couple of options.
See xref:deploy-proxy-monitoring.adoc#_indications_of_success_on_origin_and_target_clusters[Indications of success on origin and target clusters].
====

[#access-the-proxy-logs]
== Access the proxy logs

To confirm that the {product-proxy} instances are operating normally, or investigate any issue, you can view or collect their logs.

You can view the logs for a single proxy instance, or you can use a playbook to systematically retrieve logs from all instances and package them in a zip archive for later inspection.

=== View the logs

The {product-proxy} runs as a Docker container on each proxy host.
Its logs can be viewed by connecting to a proxy host and running the following command.

[source,bash]
----
docker container logs zdm-proxy-container
----

To leave the logs open and continuously output the latest log messages, append the `--follow` (or `-f`) option to the command above.

=== Collect the logs

You can easily retrieve the logs of all {product-proxy} instances using a dedicated playbook (`collect_zdm_proxy_logs.yml`).
You can view the playbook's configuration values in `vars/zdm_proxy_log_collection_config.yml`, but no changes to it are required.

Connect to the Ansible Control Host container as explained above and run:

[source,bash]
----
ansible-playbook collect_zdm_proxy_logs.yml -i zdm_ansible_inventory
----

This playbook creates a single zip file, called `zdm_proxy_logs_**TIMESTAMP**.zip`, containing the logs from all proxy instances, and stores it on the Ansible Control Host Docker container in the directory `/home/ubuntu/zdm_proxy_archived_logs`.

To copy the zip file from the container to the jumphost, open a shell on the jumphost and run the following command:

[source,bash,subs="+quotes"]
----
docker cp zdm-ansible-container:/home/ubuntu/zdm_proxy_archived_logs/**ZDM_PROXY_LOGS_ARCHIVE_NAME** **DESTINATION_DIRECTORY_ON_JUMPHOST**
----

The archive will be copied to the specified destination directory on the jumphost.

[[change-mutable-config-variable]]
== Change a mutable configuration variable

The following configuration variables are considered mutable and can be changed in a rolling fashion on an existing {product-proxy} deployment.

Commonly changed variables, located in `vars/zdm_proxy_core_config.yml`:

* `primary_cluster`:
** This variable determines which cluster is currently considered the xref:glossary.adoc#_primary_cluster[primary cluster].
At the start of the migration, the primary cluster is the origin cluster because it contains all of the data.
In Phase 4 of the migration, once all the existing data has been transferred and any validation/reconciliation step has been successfully executed, you can switch the primary cluster to be the target cluster.
** Valid values: `ORIGIN`, `TARGET`.
* `read_mode`:
** This variable determines how reads are handled by the {product-proxy}.
** Valid values:
*** `PRIMARY_ONLY`: reads are only sent synchronously to the primary cluster. This is the default behavior.
*** `DUAL_ASYNC_ON_SECONDARY`: reads are sent synchronously to the primary cluster and also asynchronously to the secondary cluster.
See xref:enable-async-dual-reads.adoc[].
** Typically, when choosing `DUAL_ASYNC_ON_SECONDARY` you will want to ensure that `primary_cluster` is still set to `ORIGIN`.
When you are ready to use the target cluster as the primary cluster, revert `read_mode` to `PRIMARY_ONLY`.
* `log_level`:
** Defaults to `INFO`.
** Only set to `DEBUG` if necessary and revert to `INFO` as soon as possible, as the extra logging can have a slight performance impact.

Other, rarely changed variables:

* Origin username/password in `vars/zdm_proxy_cluster_config.yml`
* Target username/password in `vars/zdm_proxy_cluster_config.yml`
* Advanced configuration variables in `vars/zdm_proxy_advanced_config.yml`:
** `zdm_proxy_max_clients_connections`:
*** Maximum number of client connections that the {product-proxy} should accept.
Each client connection results in additional cluster connections and causes the allocation of several in-memory structures, so this variable can be tweaked to cap the total number on each instance.
A high number of client connections per proxy instance may cause some performance degradation, especially at high throughput.
*** Defaults to `1000`.
** `replace_cql_functions`:
*** Whether the {product-proxy} should replace standard CQL function calls in write requests with a value computed at proxy level.
*** Currently, only the replacement of `now()` is supported.
*** Boolean value.
Disabled by default.
Enabling this will have a noticeable performance impact.
** `zdm_proxy_request_timeout_ms`:
*** Global timeout (in ms) of a request at proxy level.
*** This variable determines how long the {product-proxy} will wait for one cluster (in case of reads) or both clusters (in case of writes) to reply to a request.
If this timeout is reached, the {product-proxy} will abandon that request and no longer consider it as pending, thus freeing up the corresponding internal resources.
Note that, in this case, the {product-proxy} will not return any result or error: when the client application's own timeout is reached, the driver will time out the request on its side.
*** Defaults to `10000` ms.
If your client application has a higher client-side timeout because it is expected to generate requests that take longer to complete, you need to increase this timeout accordingly.
** `origin_connection_timeout_ms` and `target_connection_timeout_ms`:
*** Timeout (in ms) when attempting to establish a connection from the proxy to the origin or the target.
*** Defaults to `30000` ms.
** `async_handshake_timeout_ms`:
*** Timeout (in ms) when performing the initialization (handshake) of a proxy-to-secondary cluster connection that will be used solely for asynchronous dual reads.
*** If this timeout occurs, the asynchronous reads will not be sent.
This has no impact on the handling of synchronous requests: the {product-proxy} will continue to handle all synchronous reads and writes normally.
*** Defaults to `4000` ms.
** `heartbeat_interval_ms`:
*** Frequency (in ms) with which heartbeats will be sent on cluster connections (i.e. all control and request connections to the origin and the target).
Heartbeats keep idle connections alive.
*** Defaults to `30000` ms.
** `metrics_enabled`:
*** Whether metrics collection should be enabled.
*** Boolean value.
Defaults to `true`, but can be set to `false` to completely disable metrics collection.
This is not recommended.

** [[zdm_proxy_max_stream_ids]]`zdm_proxy_max_stream_ids`: 
*** In the CQL protocol every request has a unique id, named stream id.
This variable allows you to tune the maximum pool size of the available stream ids managed by the {product-proxy} per client connection.
In the application client, the stream ids are managed internally by the driver, and in most drivers the max number is 2048 (the same default value used in the proxy).
If you have a custom driver configuration with a higher value, you should change this property accordingly.
*** Defaults to `2048`.

Deprecated variables, which will be removed in a future {product-proxy} release:

* `forward_client_credentials_to_origin`:
** Whether the credentials provided by the client application are for the origin  cluster.
** Boolean value.
Defaults to `false` (the client application is expected to pass the target credentials), can be set to `true` if the client passes credentials for the origin cluster instead.

To change any of these variables, edit the desired values in `vars/zdm_proxy_core_config.yml`, `vars/zdm_proxy_cluster_config.yml` (credentials only) and/or `vars/zdm_proxy_advanced_config.yml` (mutable variables only, as listed above).

To apply the configuration changes to the {product-proxy} instances in a rolling fashion, run the following command:

[source,bash]
----
ansible-playbook rolling_update_zdm_proxy.yml -i zdm_ansible_inventory
----

This playbook operates by recreating each proxy container one by one.
The {product-proxy} deployment remains available at all times and can be safely used throughout this operation.
The playbook automates the following steps:

. It stops one container gracefully, waiting for it to shut down.
. It recreates the container and starts it up.
+
[IMPORTANT]
====
A configuration change is a destructive action because containers are considered immutable.
Note that this will remove the previous container and its logs.
Make sure you collect the logs prior to this operation if you want to keep them.
====
. It checks that the container has come up successfully by checking the readiness endpoint:
.. If unsuccessful, it repeats the check for six times at 5-second intervals and eventually interrupts the whole process if the check still fails.
.. If successful, it waits for 10 seconds and then moves on to the next container.

The pause between the restart of each {product-proxy} instance defaults to 10 seconds.
To change this value, you can set the desired number of seconds in `zdm-proxy-automation/ansible/vars/zdm_playbook_internal_config.yml`.

[NOTE]
====
All configuration variables that are not listed in this section are considered immutable and can only be changed by recreating the deployment.

If you wish to change any of the immutable configuration variables on an existing deployment, you will need to re-run the deployment playbook (`deploy_zdm_proxy.yml`, as documented in xref:deploy-proxy-monitoring.adoc[this page]).
This playbook can be run as many times as necessary.

Be aware that running the `deploy_zdm_proxy.yml` playbook results in a brief window of unavailability of the whole {product-proxy} deployment while all the {product-proxy} instances are torn down and recreated.
====

[[_upgrade_the_proxy_version]]
== Upgrade the proxy version

The {product-proxy} version is displayed at startup, in a message such as `Starting {product-proxy} version ...`.
It can also be retrieved at any time by using the `version` option as in the following command.

Example:

[source,bash]
----
docker run --rm datastax/zdm-proxy:<version> -version
----

Here's an example for {product-proxy} 2.1.x:

[source,bash]
----
docker run --rm datastax/zdm-proxy:2.1.x -version
----

The playbook for configuration changes can also be used to upgrade the {product-proxy} version in a rolling fashion.
All containers will be recreated with the image of the specified version.
The same behavior and observations as above apply here.

To perform an upgrade, change the version tag number to the desired version in `vars/zdm_proxy_container.yml`:

[source,bash]
----
zdm_proxy_image: datastax/zdm-proxy:x.y.z
----

Replace `x.y.z` with the version you would like to upgrade to.

{product-proxy} example:

[source,bash]
----
zdm_proxy_image: datastax/zdm-proxy:2.1.0
----

Then run the same playbook as above, with the following command:

[source,bash]
----
ansible-playbook rolling_update_zdm_proxy.yml -i zdm_ansible_inventory
----

== Scale operations with {product-automation}

{product-automation} doesn't provide a way to scale operations up or down in a rolling fashion.
If you are using {product-automation} and you need a larger {product-proxy} deployment, you have two options:

Recommended: Create a new deployment::
This is the recommended way to scale your {product-proxy} deployment because it requires no downtime.
+
With this option, you create a new {product-proxy} deployment, and then move your client application to it:
+
. xref:ROOT:setup-ansible-playbooks.adoc[Create a new {product-proxy} deployment] with the desired topology on a new set of machines.
. Change the contact points in the application configuration so that the application instances point to the new {product-proxy} deployment.
. Perform a rolling restart of the application instances to apply the new contact point configuration.
+
The rolling restart ensures there is no interruption of service.
The application instances switch seamlessly from the old deployment to the new one, and they are able to serve requests immediately.
. After restarting all application instances, you can safely remove the old {product-proxy} deployment.

Add instances to an existing deployment::
This option requires some manual effort and a brief amount of downtime.
+
With this option, you change the topology of your existing {product-proxy} deployment, and then restart the entire deployment to apply the change:

. Amend the inventory file so that it contains one line for each machine where you want to deploy a {product-proxy} instance.
+
For example, if you want to add three nodes to a deployment with six nodes, then the amended inventory file must contain nine total IPs, including the six existing IPs and the three new IPs.

. Run the `deploy_zdm_proxy.yml` playbook to apply the change and start the new instances.
+
Rerunning the playbook stops the existing instances, destroys them, and then creates and starts a new deployment with new instances based on the amended inventory.
This results in a brief interruption of service for your entire {product-proxy} deployment.

== Scale {product-proxy} without {product-automation}

If you aren't using {product-automation}, you can still add and remove {product-proxy} instances.

[#add-an-instance]
Add an instance::
. Prepare and configure the new {product-proxy} instances appropriately based on your other instances.
+
Make sure the new instance's configuration references all planned {product-proxy} cluster nodes.
. On all {product-proxy} instances, add the new instance's address to the `ZDM_PROXY_TOPOLOGY_ADDRESSES` environment variable.
+
Make sure to include all new nodes.
. On the new {product-proxy} instance, set the `ZDM_PROXY_TOPOLOGY_INDEX` to the next sequential integer after the greatest one in your existing deployment.
. Perform a rolling restart of all {product-proxy} instances, one at a time.

Vertically scale existing instances::
Use these steps to increase or decrease resources for existing {product-proxy} instances, such as CPU or memory.
To avoid downtime, perform the following steps on one instance at a time:
+
. Stop the first {product-proxy} instance that you want to modify.
. Modify the instance's resources as required.
+
Make sure the instance's IP address remains the same.
If the IP address changes, you need to <<add-an-instance,treat it as a new instance>>.
. Restart the modified {product-proxy} instance.
. Wait until the instance starts, and then confirm that it is receiving traffic.
. Repeat these steps to modify each additional instance, one at a time.

Remove an instance::
. On all {product-proxy} instances, remove the unused instance's address from the `ZDM_PROXY_TOPOLOGY_ADDRESSES` environment variable.
. Perform a rolling restart of all remaining {product-proxy} instances.
. Clean up resources used by the removed instance, such as the container or VM.

== Purpose of proxy topology addresses

When you configure a {product-proxy} deployment, either through {product-automation} or manually-managed {product-proxy} instances, you specify the addresses of your instances.
These are populated in the `ZDM_PROXY_TOPOLOGY_ADDRESSES` variable, either manually or automatically depending on how you manage your instances.

{cass-short} drivers look up nodes on a cluster by querying the `system.peers` table.
{product-proxy} uses the topology addresses to effectively respond to the driver's request for connection nodes.
If there are no topology addresses specified, {product-proxy} defaults to a single-instance configuration.
This means that driver connections will use only that one {product-proxy} instance, rather than all instances in your {product-proxy} deployment.

If that one instance goes down, {product-proxy} won't know that there are other instances available, and your application can experience an outage.
Additionally, if you need to restart {product-proxy} instances, and there is only one instance specified in the topology addresses, your migration will have downtime while that one instance restarts.

== See also

* xref:ROOT:troubleshooting-tips.adoc[]
* xref:ROOT:troubleshooting-scenarios.adoc[]