= Migration paths
:navtitle: Migration Paths
:page-tag: migration,zdm,zero-downtime,zdm-proxy,introduction
//ifdef::env-github,env-browser,env-vscode[:imagesprefix: ../images/]
//ifndef::env-github,env-browser,env-vscode[:imagesprefix: ]

{company} offers a set of thoroughly-tested self-service tools, automation scripts, examples, and documented procedures that walk you through well-defined migration phases.

These tools are a simple and reliable way for you to migrate applications from any CQL-based cluster such as https://cassandra.apache.org/_/index.html[Apache Cassandra&reg;], https://www.datastax.com/products/datastax-enterprise[DataStax Enterprise (DSE)], https://www.datastax.com/products/datastax-astra[{astra_db}], or any type of CQL-based database to any other CQL-based cluster, without any interruption of service to the client applications and data.


include::partial$note-downtime.adoc[]

[TIP]
====
The {zdm-product} process requires you to be able to perform rolling restarts of your client applications during the migration.

This is standard practice for client applications that are deployed over multiple instances and is a widely used approach to roll out releases and configuration changes.
====


include::partial$supported-releases.adoc[]

There are many reasons to migrate your data and client applications from one cluster to another:

* Moving to a different type of CQL database, for example an on-demand cloud-based proposition such as {astra_db}.

* Upgrading a cluster to a newer version, or newer infrastructure, in as little as one step while leaving your existing cluster untouched throughout the process.

* Moving one or more client applications out of a shared cluster and onto a dedicated one to manage and configure each cluster independently.

* Consolidating client applications, which may be currently running on separate clusters, onto a shared one to reduce overall database footprint and maintenance overhead.

The following are our migration paths/scenarios available when using one of {company} migration tools:

* From an existing self-managed DSE cluster to cloud-native {astra_db}: DSE 4.7.1+, 4.8.x, 5.1.x, 6.7.x or 6.8.x to {astra_db}.
For more, see xref: https://docs.datastax.com/en/dse/6.8/overview/overview.html[DSE 6.8] or https://docs.datastax.com/en/dse/5.1/overview/overview.html[DSE 5.1].

* From an existing DSE cluster to another DSE cluster: DSE 4.7.1+, 4.8.x, 5.1.x or 6.7.x to DSE 6.8.x.
For more, see xref: https://docs.datastax.com/en/dse/6.8/overview/overview.html[DSE 6.8] or https://docs.datastax.com/en/dse/5.1/overview/overview.html[DSE 5.1].

* From https://docs.datastax.com/en/astra-classic/docs[{astra_db} Classic] to https://docs.datastax.com/en/astra/astra-db-vector/[{astra-db-serverless}].
For more, see https://docs.datastax.com/en/astra-db-serverless/index.html[{company} Astra DB Serverless]

* From any CQL-based database type/version to the equivalent CQL-based database type/version. 

include::partial$note-downtime.adoc[] 

[TIP]
====
An important migration prerequisite is that you already have the matching schema on target.
A CQL statement that your client application sends to {zdm-proxy} must be able to succeed on both origin and target clusters.
This means that any keyspace that your client application uses must exist on both origin and target clusters with the same name.
Table names must also match.
For more, see xref:feasibility-checklists.adoc#_schemakeyspace_compatibility[Schema/keyspace compatibility].
====
