= Prepare to use {sstable-sideloader}
:description: Before you use {sstable-sideloader}, review the requirements and prepare your target database, origin cluster, and administration server.

{description}

== Target {astra-db} database requirements

* Your {astra-db} organization must be on an *Enterprise* xref:astra-db-serverless:administration:subscription-plans.adoc[subscription plan].
+
{sstable-sideloader} is a premium feature that incurs costs based on usage:
+
** Total amount (GB) of data processed as part of the {sstable-sideloader} workload.
** The amount of data stored in the migration bucket is metered at the standard {astra-db} storage rate.

+
--
For more information and specific rates, see the https://www.datastax.com/pricing/astra-db[{astra-db} Pricing page].

[TIP]
====
Migration directories are automatically cleaned up after one week of idle time.

To minimize costs, you can xref:sideloader:cleanup-sideloader.adoc[manually cleanup migration directories] when you no longer need them.
====
--

* Your target database must be an {astra-db} Serverless database.
If you don't already have one, xref:astra-db-serverless:databases:create-database.adoc[create a database].
You can use either a {db-serverless} or {db-serverless-vector} database, and {db-serverless-vector} databases can store both vector and non-vector data.

* Your target database must be in a PCU group.
You can use either a flexible capacity or committed capacity PCU group, depending on your long-term needs and other PCU group usage.
+
[tabs]
======
Flexible capacity PCU group::
+
--
Because {sstable-sideloader} operations are typically short-term, resource-intensive events, you can create a flexible capacity PCU group exclusively to support your target database during the migration.

//After PCU PR merge: xref:astra-db-serverless:administration:create-pcu.adoc#flexible-capacity[create a flexible capacity PCU group]

After the migration, you can move your target database out of the flexible capacity PCU group, and then park or delete the group.
Don't park the PCU group during the {sstable-sideloader} process because databases in a parked PCU group are hibernated and unavailable for use.
--

Committed capacity PCU group::
+
--
If you plan to keep your target database in a PCU group after the migration, you can create a committed capacity PCU group for your target database.

//After PCU PR merge: xref:astra-db-serverless:administration:create-pcu.adoc#committed-capacity[create a committed capacity PCU group]

The {sstable-sideloader} process can be extremely resource intensive.
If there are any other databases in the same PCU group, the migration process can affect their performance due to resource contention.

If your PCU groups have multiple databases, consider using a flexible capacity PCU group to temporarily isolate your target database during the migration.

{company} recommends the following committed capacity PCU group configuration for {sstable-sideloader} migrations:

* Reserved capacity: 1 or more, depending on the PCU group's normal, long-term workload requirements.
+
This is the amount of capacity that you want the group to have after the migration is complete.

* Minimum capacity: Equal or greater than the reserved capacity.
+
If the minimum is greater than the reserved capacity, your PCU group has consistent access to that capacity until you reduce it.
{company} recommends this to prepare the additional capacity in advance, rather than facing potential, temporary resource shortages while autoscaling.

* Maximum capacity: Greater than the minimum by several units.
+
This allows the group to access surplus capacity during resource intensive stages of the migration.
+
For any non-trivial migration, consider setting the maximum to 10.
For extremely large migrations, contact your {company} account representative or {support-url}[{company} Support] to request more than 10 units to support your migration.
--
======
+
For more information, see xref:astra-db-serverless:administration:provisioned-capacity-units.adoc[].

[#origin-cluster-requirements]
== Origin cluster requirements

The following requirements, recommendations, and limitations apply to origin clusters.
Review all of these to ensure that your cluster is compatible with {sstable-sideloader}.

=== Cluster infrastructure

* Your origin cluster can be hosted on premises or on any cloud provider.

* Your origin cluster must run a supported database version:
+
** OSS {cass-short} 3.11 or later
** {dse-short} 5.1 or later
** {hcd-short} 1.1 or later
//Due to a potential occasional issue affecting SSTables generated by C* 3.0 / DSE 5.0. Until the fix is rolled out, we need to restrict the SSTable versions.

* Your origin cluster must use the default https://cassandra.apache.org/doc/stable/cassandra/configuration/cass_yaml_file.html#partitioner[partitioner], `Murmur3Partitioner`.
+
Older partitioners, such as `RandomPartitioner`, `ByteOrderedPartitioner`, and `OrderPreservingPartitioner`, are not supported.

=== Cloud provider CLI

To upload snapshots directly from the origin cluster, you must install your cloud provider's CLI on each node in the origin cluster.

The tool you install depends on the region where your target {astra-db} database is deployed:

* AWS regions: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Install AWS CLI]
* Google Cloud regions: https://cloud.google.com/sdk/docs/install-sdk[Install gcloud] and https://cloud.google.com/storage/docs/gsutil_install[install gsutil]
* Microsoft Azure regions: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[Install Azure CLI]

Alternatively, you can upload copies of the snapshots from a separate staging server that has the CLI installed, and you must coordinate this through the administration server.
However, this process _isn't_ covered in this guide.
The CLI commands in this guide assume you have installed your cloud provider's CLI on the nodes in the origin cluster.
If you choose the alternative option, you must modify the commands accordingly for your environment.

=== Incompatible data

* *{astra-db} doesn't support materialized views*: You must replace these with SAI or an alternative data model design.

* *{sstable-sideloader} doesn't support encrypted data*: If your origin cluster uses xref:6.9@dse:securing:transparent-data-encryption.adoc[{dse-short} Transparent Data Encryption], be aware that {sstable-sideloader} can't migrate these SSTables.
+
If you have a mix of encrypted and unencrypted data, you can use {sstable-sideloader} to migrate the unencrypted data.
After the initial migration, you can use another strategy to move the encrypted data, such as https://github.com/datastax/cassandra-data-migrator[{cass-short} Data Migrator (CDM)] or a manual export and reupload.

* *{sstable-sideloader} doesn't support secondary indexes*: If you don't remove or replace these in your origin cluster, then you must manually remove these directories from your snapshots, as explained in xref:sideloader:migrate-sideloader.adoc#create-snapshots[Create snapshots].

== Administration server requirements

You need a server where you can run the {sstable-sideloader} commands.

Your administration server must have SSH access to each node in your origin cluster.

{company} recommends that you install the following additional software on your administration server:

* https://github.com/datastax/cassandra-data-migrator[{cass-short} Data Migrator (CDM)] to validate imported data and, in the context of {product}, reconcile it with the origin cluster.
* https://jqlang.github.io/jq/[jq] to format JSON responses from the {astra-db} {devops-api}.
The {devops-api} commands in this guide use this tool.

== Multi-region deployments

If you need to migrate data that is replicated to multiple regions, contact your {company} account representative or {support-url}[{company} Support] for assistance with planning your migration.

== Next steps

* xref:sideloader:migrate-sideloader.adoc[]