= Troubleshoot {sstable-sideloader}
:description: Get help with {sstable-sideloader}

Learn how to troubleshoot common {sstable-sideloader} issues.

== Migration status is outdated

You can use the {devops-api} to check the migration status at any time.
However, it can take a few minutes for the {devops-api} to reflect status changes during a migration.
Immediately calling the {devops-api} after starting a new phase of the migration might not return the actual current status.

[#get-new-upload-credentials]
== Get new upload credentials

//TODO: Does checking the migration status always generate new creds or only if they are expired?

If your credentials expire, do the following:

. Use the `MigrationStatus` endpoint to generate new credentials:
+
include::sideloader:partial$sideloader-partials.adoc[tags=check-status]

. Continue the migration with the fresh credentials.
+
If you set environment variables for your credentials, be sure to update those values.

== Retry a failed migration

If a migration fails, there are two ways that you can reattempt the migration.
The option you use depends on the type of error that occurred.

If you are able to resolve the cause of the failure without modifying the migration directory contents, you can relaunch the migration using the data already present in the migration directory.
Otherwise, you must abandon the failed migration and restart the entire migration process from the beginning.

The two most common errors are as follows:

* *Schema discrepancies*: There is a mismatch between the origin and target schemas.
To resolve this error, you can align the schemas and then <<relaunch,relaunch the migration>>.

* *Invalid data in migration directory*: The data uploaded to the migration directory is invalid or improperly formatted.
Common cause include data corruption, incomplete upload due to a timeout, malformed file paths, and the presence of invalid data such as secondary index directories.
+
When this type of failure occurs, you must abandon the failed migration and restart the entire migration process.
For more information, see <<restart>>.

[#relaunch]
=== Relaunch a failed migration

//TODO: questions on doc-4510 for relaunch

. Check the migration status for an error message related to the failure:
+
include::sideloader:partial$sideloader-partials.adoc[tags=check-status]

. If possible, resolve the issue described in the error message.
+
For example, if there is a problem with the schema in the target database, make sure that your schemas align, as described in xref:sideloader:migrate-sideloader.adoc#record-schema[Configure the target database].

. Repeat the `launch` command that you used to xref:sideloader:migrate-sideloader.adoc#import-data[import the data], and continue the migration process from there.

If the migration fails again, see <<restart>>.

////
Future:
=== Reset failed migration endpoint
https://datastax.slack.com/archives/C044Q060210/p1741772318884679?thread_ts=1741691860.400749&cid=C044Q060210
TODO: Add to this page and stop-restart page.

"resetting" a failed/aborted migration:
- Call a new endpoint called reset, which removes all the metadata and restores their write and read access to the migration directory.
- By doing this they accept that the progress will be wiped and that they will be charged for the failed attempt in accordance with our pricing rules.
- Amend the data in the migration directory as needed.
- Call relaunch to re-execute the migration from scratch.
////

[#restart]
=== Restart a failed migration

When a migration fails due to a problem with the data uploaded to the migration directory, you must completely restart the migration.

. Review the xref:sideloader:prepare-sideloader.adoc#origin-cluster-requirements[origin cluster requirements] to ensure that your snapshot doesn't contain invalid data, including materialized views, encrypted data, and secondary indexes.

. If necessary, xref:sideloader:migrate-sideloader.adoc#create-snapshots[create new snapshots] of any invalid snapshots.

. If necessary, xref:sideloader:migrate-sideloader.adoc#record-schema[reprepare the target database].
There are two reasons you might need to do this:
+
** The origin and target schemas don't match.
** The migration reached a point that some data was loaded to the target database.
This is unlikely, but, if this happens, you must xref:astra-db-serverless:databases:manage-collections.adoc#delete-a-table-in-the-astra-portal[drop the table] from your target database, and then recreate the table in the target database.

. Repeat the remainder of the migration process from xref:sideloader:migrate-sideloader.adoc#initialize-migration[Initialize the migration].
+
This starts a fresh migration with a new migration directory, a migration ID, and upload credentials.

. If the migration fails again and you are unable to determine the cause of the failure, contact {support-url}[{company} Support].

//Technically, if they didn't remove SI from their snapshots, DS could remove those directories from the migration bucket.