= Change the read routing

This topic explains how you can configure the ZDM proxy to route all reads to the target database (in our case Astra DB) instead of your Origin database.

You would typically do this once you have migrated all the existing data from your Origin cluster and completed all validation checks and reconciliation if necessary.

This operation is a configuration change that can be carried out as explained xref:migration-manage-proxy-instances.adoc#change-mutable-config-property[here].

If you're not there already, `ssh` back into the jumphost:

```bash
ssh -F ~/.ssh/zdm_ssh_config jumphost
```

On the jumphost, connect to the Ansible Control Host container:
```bash
docker exec -it zdm-ansible-container bash
```
You will see a prompt like:
```bash
ubuntu@52772568517c:~$
```

Now open the proxy core configuration file for editing. Example:

```bash
cd zdm-proxy-automation/ansible
nano vars/zdm_proxy_core_config.yml
```

Change the flag `forward_reads_to_target` to `true`.

Run the playbook that changes the configuration of the existing proxy deployment:

```bash
ansible-playbook update_zdm_proxy.yml -i zdm_ansible_inventory
```

Wait for the proxies to be restarted by Ansible, one by one. All proxy instances will now send all reads to Target (Astra DB) instead of Origin. In other words, Target is now the primary source of truth, but the proxy is still keeping Origin up-to-date.

[ TODO ensure this ties in with the examples so far ]
Repeat the same reads through the ZDM Demo Client application:

```bash
curl -G -d 'rowkey=250' http://localhost:8080/zdm-demo-client/rest/row
curl -G -d 'rowkey=1000' http://localhost:8080/zdm-demo-client/rest/row
curl -G -d 'rowkey=1080' http://localhost:8080/zdm-demo-client/rest/row
```

The resulting data is identical because the two databases are in sync.

== What's next? 

Learn how to xref:migration-connect-apps.adoc[Connect your clients directly to Astra DB].
