= DataStax Zero Downtime Migration Release Notes

The Zero Downtime Migration (ZDM) project provides a production-ready set of tools to help you migrate to another version of Apache Cassandra&reg; or DataStax Enterprise, or to cloud-native Astra DB. 

== Release Notes for ZDM 2.0.0

03 October 2022

=== Components 

Open source:

* ZDM-Proxy

Tools and examples in public GitHub repos for your use, but not open source or available for code contributions:

* ZDM Automation utility
* DSBulk Migrator
* Cassandra Data Migrator

== GitHub repos

The following DataStax migration repos are public. You are welcome to read the source and submit feedback via GitHub Issues per repo. At this time, code contributions from Pull Requests are not supported.

* https://github.com/datastax/zdm-proxy[ZDM-Proxy^] repo.

* https://github.com/datastax/migration-docs[Migration documentation^] repo.

* https://github.com/datastax/zdm-proxy-automation[ZDM-Proxy Automation utility^] repo. 

* https://github.com/riptano/cloud-gate-schema-migrator[DSBulk Migrator^] repo. (Internal Note: Repo location and name will change - to be determined.)

* https://github.com/datastax/cassandra-data-migrator[Cassandra Data Migrator^] repo. (Internal Note: To be setup.)

=== Supported environments

With the {company} {product} 2.0.0 release, you can migrate any Cassandra Query Language (CQL) compliant database cluster from its origin (current) environment to a new target. Migration examples:

* From an existing self-managed Cassandra or DSE cluster to cloud-native Astra DB or vice versa. For example, migrate:
** Cassandra 3.11.x or 4.0.x to Astra DB
** DSE 5.1.x or 6.8.x to Astra DB
* From an existing Cassandra or DSE cluster to another Cassandra or DSE cluster. For example, migrate:
** Cassandra 3.11.x to 4.0.x
** DSE 5.1.x to DSE 6.8.x
* From Astra DB Classic to Astra DB Serverless

=== ZDM-Proxy 2.0.0 revisions

See the https://github.com/datastax/zdm-proxy/blob/main/CHANGELOG/CHANGELOG-2.0.md(CHANGELOG-2.0) for details about ZDM-Proxy open-source code.

