= Change the read routing

This topic explains how you can configure the {zdm-proxy} to route all reads to Target instead of Origin.

You would typically do this once you have migrated all the existing data from Origin and completed all validation checks and reconciliation if necessary.

This operation is a configuration change that can be carried out as explained xref:migration-manage-proxy-instances.adoc#change-mutable-config-property[here].

If you're not there already, `ssh` back into the jumphost:

```bash
ssh -F ~/.ssh/zdm_ssh_config jumphost
```

On the jumphost, connect to the Ansible Control Host container:
```bash
docker exec -it zdm-ansible-container bash
```
You will see a prompt like:
```bash
ubuntu@52772568517c:~$
```

Now open the configuration file `vars/zdm_proxy_core_config.yml` for editing.

Change the variable `primary_cluster` to `TARGET`.

Run the playbook that changes the configuration of the existing {zdm-proxy} deployment:

```bash
ansible-playbook rolling_update_zdm_proxy.yml -i zdm_ansible_inventory
```

Wait for the {zdm-proxy} instances to be restarted by Ansible, one by one. All instances will now send all reads to Target instead of Origin. In other words, Target is now the primary cluster, but the {zdm-proxy} is still keeping Origin up-to-date.