= Tools to migrate and validate data

This topic introduces you to the benefits of using two free, open-source data migration tools during your migration project:

* {cstar-data-migrator}
* {dsbulk-migrator}

These tools provide helpful features and may be used to match the requirements of your Apache Cassandra&reg;, DataStax Enterprise (DSE), or Astra DB databases.  The tools can help you migrate data from any Cassandra Origin (Cassandra/DSE/Astra DB) to any Cassandra Target (Cassandra/DSE/Astra DB).

== What's the difference between these data migration tools?

In general:

* {cstar-data-migrator} is the best choice to migrate large data quantities, and where detailed verifications and reconciliation options are needed.

* {dsbulk-migrator} leverages {company} Bulk Loader (DSBulk) to perform the actual data migration, and provides new commands specific to migrations. {dsbulk-migrator} is ideal for migration of small data quantities, such as databases that have less than 20 GBs of data in the table rows.  

== How do I install and use these data migration tools?

They're available in the following GitHub repos:

* https://github.com/datastax/cassandra-data-migrator[Cassandra Data Migrator^] repo.

* https://github.com/datastax/dsbulk-migrator[DSBulk Migrator^] repo.

Refer to the README in each repo for the latest, detailed instructions to install and use these data migrators. The READMEs include prerequisites, download resources, configuration, and command-line usage information. 

== Summary of features 

Here's a quick summary of the features per data migration tool. See each repo's README for details. 

=== {cstar-data-migrator}

For large data migrations, including cases where advanced logging is needed, {cstar-data-migrator} is designed to:

* Connect to and compare your Target database with Origin
* Report differences in a detailed log file
* Reconcile any missing records and fix any data inconsistencies in the target, if you enable `autocorrect` in a config file

{cstar-data-migrator} runs in a lightweight, easily set up Apache Spark wrapper. For example, you can configure a `sparkConf.properties` file for the environment. There's a sample https://github.com/Ankitp1342/astra-spark-migration-ranges/blob/master/src/resources/sparkConf.properties[sparkConf.properties] configuration example in the GitHub repo.

In its settings, you'll identify values for your Origin and Target databases. A subset example:

[source]
----
spark.migrate.origin.isAstra                               false
spark.migrate.origin.host                                  localhost
spark.migrate.origin.username                              some-username
spark.migrate.origin.password                              some-secret-password
spark.migrate.origin.read.consistency.level                LOCAL_QUORUM
spark.migrate.origin.keyspaceTable                         test.a1

spark.migrate.target.isAstra                               true
spark.migrate.target.scb                                   file:///aaa/bbb/secure-connect-enterprise.zip
spark.migrate.target.username                              client-id
spark.migrate.target.password                              client-secret
spark.migrate.target.read.consistency.level                LOCAL_QUORUM
spark.migrate.target.keyspaceTable                         test.a2
spark.migrate.target.autocorrect.missing                   false
spark.migrate.target.autocorrect.mismatch                  false
----

[TIP]
====
An important **prerequisite** is that you already have the matching schema on Target. For every table migrated by Cassandra Data Migrator, the tool can use a mapping configuration that links every Origin column to every Target column.
====

The validation checks are a way to verify that all the data has been migrated successfully. For data written by idempotent writes these checks are optional, as any errors, timeouts or other failures during the migration are made visible by the {cstar-data-migrator} and by {zdm-proxy}.

In the case of data written by non-idempotent writes, it is necessary to reconcile and realign any discrepancies before starting to use Target as the primary cluster.

For installation and usage details, see the {cstar-data-migrator} repo's https://github.com/datastax/cassandra-data-migrator/blob/main/README.md[README, window="_blank"]. 

=== {dsbulk-migrator}

{dsbulk-migrator}, which is based on {company} Bulk Loader (DSBulk), is best for migrating smaller amounts of data, and/or when you can shard data from table rows into more manageable quantities.  

{dsbulk-migrator} provides the following main commands:

* `migrate-live` starts a live data migration using a pre-existing DSBulk installation, or alternatively, the embedded DSBulk version. A "live" migration means that the data migration will start immediately and will be performed by this migrator tool through the desired DSBulk installation.

* `generate-script` generates a migration script that, once executed, will perform the desired data migration, using a pre-existing DSBulk installation. Please note: this command does not actually migrate the data; it only generates the migration script.

* `generate-ddl` reads the schema from Origin and generates CQL files to recreate it in an Astra DB cluster used as Target.

For installation and usage details, see the {dsbulk-migrator} repo's https://github.com/datastax/dsbulk-migrator/blob/main/README.md[README, window="_blank"]. 
