= Configure Transport Layer Security (TLS)

{zdm-proxy} supports proxy-to-cluster and application-to-proxy TLS encryption.

The TLS configuration is an optional part of the initial {zdm-proxy} configuration. See the information here in this topic, and then refer to the {zdm-automation} topics that cover:

* xref:migration-setup-ansible-playbooks.adoc[]
* xref:migration-run-ansible-playbooks.adoc[]

== Introduction

* All TLS configuration is optional. Enable TLS between the {zdm-proxy} and any cluster that requires it, and/or between your client application and the {zdm-proxy} if required.

* Proxy-to-cluster TLS can be configured between the {zdm-proxy} and Origin / Target (either or both) as desired. Each set of configuration is independent of the other. When using proxy-to-cluster TLS, the {zdm-proxy} acts as the TLS client and the cluster as the TLS server. One-way TLS and Mutual TLS are both supported and can be enabled depending on each cluster's requirements.

* When using application-to-proxy TLS, your client application is the TLS client and the {zdm-proxy} is the TLS server. One-way TLS and Mutual TLS are both supported.

* When the {zdm-proxy} connects to Astra DB clusters, it always implicitly uses Mutual TLS. 
This is done through the Secure Connect Bundle (SCB) and does not require any extra configuration.

[#retrieve-files-from-jks]
== Retrieving files from a JKS keystore

If you are already using TLS between your client application and Origin, the files needed to configure TLS will already be used in the client application's and Origin's configuration. In some cases, these files may be contained in a JKS keystore.

The {zdm-proxy} does not accept a JKS keystore, requiring the raw files instead.

To view the files contained in a JKS keystore and their aliases:

```bash
keytool -list -keystore <path_to_keystore.jks>
```

To extract a file from a JKS keystore:

```
keytool -exportcert -keystore <path_to_jks_store> -alias <file_alias> -file <path_to_destination_file> -rfc
```

Please note the `-rfc` option, which extracts the files in non-binary PEM format.

For more details, see the https://docs.oracle.com/javase/8/docs/technotes/tools/windows/keytool.html[keytool syntax documentation^].

== Proxy to self-managed cluster TLS

Here's how to configure TLS between the {zdm-proxy} and a self-managed cluster. In this case the {zdm-proxy} acts as the TLS client and the cluster acts as the TLS server.

The files required to configure proxy-to-cluster TLS are:

* Server CA: needed for one-way and Mutual TLS
* Client certificate: only needed for Mutual TLS
* Client key: only needed for Mutual TLS

If your Origin cluster requires TLS, your client application will already be using these files when configuring its connection to it.

There is a set of TLS configuration properties for Origin and a separate one for Target, so that they can be configured independently as desired.

=== Prepare the TLS files

For each TLS-enabled cluster (Origin and/or Target), create a directory on the Ansible Control Host (for example, `origin_tls_files` and / or `target_tls_files`). This directory is only needed for self-managed clusters requiring TLS.

Copy the necessary TLS files to each directory:

* For one-way TLS, only the server CA.

* For Mutual TLS, the server CA, the client cert and the client key.

[TIP]
====
All files must be in plain-text, non-binary format.
====

Edit the relevant values in the configuration file `vars/zdm_proxy_custom_tls_config.yml` as follows.

* For proxy-to-Origin TLS configuration:

 ** `origin_tls_user_dir_path`: path to the directory you created on the Ansible Control Host containing the TLS files for Origin; for example, `/home/ubuntu/origin_tls_files`.

 ** `origin_tls_server_ca_filename`: filename (without path) of the Server CA.

 ** `origin_tls_client_cert_filename`: filename (without path) of the Client cert. This is for Mutual TLS only, leave unset otherwise.

 ** `origin_tls_client_key_filename`: filename (without path) of the Client key. For Mutual TLS only, leave unset otherwise.

* The configuration for proxy-to-Target TLS is done in the same way but using the Target-specific configuration parameters (`target_tls_*`).

== Application-to-proxy TLS

Here are the steps to enable TLS between your client application and the {zdm-proxy} if required. Please bear in mind that in this case your client application is the TLS client and the {zdm-proxy} is the TLS server.

The files required by the proxy to configure application-to-proxy TLS are:

* Server CA
* Server certificate
* Server key

All these files are required for one-way and Mutual TLS.

If your Origin cluster currently requires TLS, it will already be using these files for its own TLS configuration.

To configure application-to-proxy TLS you need to:

* Create a directory on the jumphost (for example `/home/ubuntu/proxy_tls_files`) and copy all necessary TLS files to it.

* Populate the relevant configuration variables.

The relevant variables are in the bottom section of `vars/proxy_custom_tls_config_input.yml` and are all prefixed with `proxy_` :

* `proxy_tls_user_dir_path_name`: directory on the Ansible Control Host where you placed all the necessary TLS files for application-to-proxy TLS. Always required.

* `proxy_tls_server_ca_filename`:  filename (without path) of the server CA that the proxy must use. Always required.

* `proxy_tls_server_cert_filename` and `proxy_tls_server_key_filename` : filenames (without path) of the server certificate and server key that the proxy must use. Both always required.

* `proxy_tls_require_client_auth`: whether you want to enable Mutual TLS between the application and the proxy. Optional: defaults to `false` ( = one-way TLS ), can be set to true to enable Mutual TLS.

[TIP]
====
Remember that in this case, the {zdm-proxy} is the TLS server; thus the word `server` word in these variable names.
====

== Applying the TLS configuration
This is all you need to do at this stage. This configuration will be applied when you run the deployment playbook (`deploy_zdm_proxy.yml`). The playbook will distribute the files to each {zdm-proxy} instance and apply the TLS configuration to it.

== What's next?

Finish configuring and deploy the {zdm-proxy}  as explained in xref:migration-run-ansible-playbooks.adoc[].

