= Connect your client applications directly to Target

At this point in our migration phases, we've completed:

* Phase 1: Connected client applications to {zdm-proxy}, which included setting up Ansible playbooks with the {zdm-utility}, and deploying the {zdm-proxy} instances via the Docker container with {zdm-automation}.

* Phase 2: Migrated and validated our data with {cstar-data-migrator} and/or {dsbulk-migrator}.

* Phase 3: Enabled async data reads (an optional step) to check that Target can handle the read/write traffic.

* Phase 4: Changed read routing to Target.

Now we're ready to perform Phase 5, configure our clients to connect directly to Target.  In this example, we'll use Astra DB as the Target. You may have already created an Astra DB database, but here we'll refer you to a few documentation topics just in case.

[TIP]
====
While this topic focuses on Astra DB as the Target, you can provision and create your cluster of choice with any CQL-based  configuration to which you want to migrate. Then if you haven't already, create the application schema by submitting a `DESCRIBE` statement on Origin and applying that schema on Target.
====

In the https://astra.datastax.com[Astra Portal^] user interface, you can easily create a cloud-native database. Once logged in, you'll have a default Organization. If you haven't already, follow the dialogs on the Dashboard to create a database and assign an appropriate region. Later, you can designate multiple regions for your database, if needed.

== Connection options

You have several options when it comes to connecting your clients to Target. Astra DB, for example, supports the following DataStax drivers. The links in this list go to Astra DB topics that describe the drivers in detail:

* https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-cplusplus.html[C++ driver^]

* https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-csharp.html[C# driver^]

* https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html[Java driver^]

* https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-nodejs.html[Node.js driver^]

* https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-python.html[Python driver^]

Be sure to also consult https://docs.datastax.com/en/dev-app-drivers/docs/bestPractices.html[Best practices for DataStax drivers] for rules and recommendations to improve performance and minimize resource utilization in client applications. 

== Connecting with Java cloud-native driver

Taking the Java cloud-native driver as an example, the **prerequisites** to connect from a Java client to an Astra DB as Target are as follows:

. Through the https://astra.datastax.com[Astra Portal^] user interface, generate a Bearer Token and select **API Administrator User** for the role.

. Create a keyspace.

. Create one of more database table(s) for your keyspace that match Origin database's schema; for an example, see https://docs.datastax.com/en/astra-serverless/docs/develop/dev-with-rest.html#_create_a_table_in_your_keyspace[Create a table in your keyspace].

. Ensure that a https://adoptopenjdk.net/[Java Development Kit (SDK)^] and https://maven.apache.org/install.html[Apache Maven^] are installed.

You would then:

. Add the DataStax Java driver dependency to your pom.xml file; for an example, see https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html#_example_pom_xml_file[this page^].

. Create your connection as outlined in this https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html#_connecting_with_java_cloud_native_driver[Java example^]. In this case, the example uses the open-source Stargate API to fetch an auth token in the demonstrated call. 


== Connecting with legacy drivers

With the legacy drivers, the **prerequisites** for connecting to Target (Astra DB in this example) are slightly different. 

. Create your database and set your environment variables to save time developing on your database. There are four environment variables needed; three of which are found on your Dashboard in https://astra.datastax.com[Astra Portal^]:
+
* `database id`
* `region`
* `keyspace`
+
In addition, there's an ID (a token) that you must create. For background steps, refer to https://docs.datastax.com/en/astra-serverless/docs/manage/db/manage-create.html[Create your database^].

. If you haven't already, https://maven.apache.org/download.cgi[download^] and https://maven.apache.org/install.html[install^] Maven.

. Get a `Client ID` and `Client Secret` from a resource called the Secure Connect Bundle (SCB) -- which you'll generate in the Astra Portal -- by creating your application token for your username and password.

=== Working with the Secure Connect Bundle ZIP file

To connect to your Astra DB database using the drivers, download the SCB from Astra Portal, which will generate the connection credentials. Here are the steps:

. From your Dashboard page in Astra Portal, select your database.
. On the Overview page, select Connect.
. In the **Select a Method** section, select Drivers and then Legacy from the dropdown menu to select your driver type from the list to load language-specific instructions.
. Click **Download Bundle**.

The `secure-connect-database_name.zip` file downloads, which contains the security certificates and credentials for your database. 

After you create an Astra DB database, you can grant access to other members of your team by providing them with the database credentials and connection details for your database.

=== Connecting the Java driver to Target

The full version of the following steps are shown in https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html#_connecting_the_driver_2[this topic].

. Navigate to the pom.xml file at the root of your Java project and open it for editing.

. Add the DataStax Java driver dependency to your pom.xml file, ensuring that the name of the dependency corresponds to the installed version: This dependency causes Maven to automatically download the appropriate .jar files found at the url specified in the repository for the DSE Java driver and make them available to your code.  See the https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html#_connecting_the_driver_2[full topic] for a pom.xml example.

. Save and close your pom.xml file.

. Initialize the DataStax Java driver.

. To test, consider creating a new source client application in the `/src/main/java` directory for your Java project. For an example in Java, see the https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html#_connecting_the_driver_2[full topic]. The example there implements a `ConnectDatabase` class to connect to your Target, runs a CQL query, and prints the output to the console.

. In that example, it's noted how you would customize source methods as follows:

 * Use `withCloudSecureConnectBundle()` method to specify the path to the secure connect bundle for your Target.
 * Use the `withAuthCredentials()` method to specify the username and password for your Target.
 * Use the `withKeyspace()` method to specify the keyspace name for your Target.

Additional details are available in the https://docs.datastax.com/en/astra-serverless/docs/connect/drivers/connect-java.html[DataStax Java Driver^] topic. 

== Example switching to Target from your client application

It's a simple process. Stop your client application(s) and start it again with `connectionMode` set to `TARGET`. Example:

```bash
mvn jetty:run -DconnectionMode=TARGET
```

All the client application(s) will now connect directly to Astra DB, and Origin is no longer being updated.

== Phase 5 of migration completed

Until this point, in case of any issues, you could have abandoned the migration and rolled back to connect directly to Origin at any time. From this point onward, the clusters will diverge, and Target is the source of truth for your applications and data. 
