= Prepare your existing environment for migration

In this topic, we'll discuss the steps you'll perform to prepare your existing cluster for migration to a new environment.

We'll use this example scenario: migration an Apache Cassandra&reg; or DataStax Enterprise (DSE) cluster to Astra DB.

Of course, your existing Cassandra or DSE cluster has database tables, populated with data, and client apps that interact in real time with the database.

[NOTE]
====
(**Alice's note:** we should briefly define the {cstar-data-migrator}, and include some advice here on the infrastructure specs for the machine(s) used to run it. This is not currently documented anywhere. Experience from the Field team will help.)
====

== {cstar-data-migrator}

{cstar-data-migrator} is designed to:

* Connect to, and compare your target database with the origin
* Report differences in a detailed log file
* Reconcile any missing records and fix any data inconsistencies in the target, if you enable `autocorrect` in a config file

For details about installing and using {cstar-data-migrator}, see xref:migration-migrate-and-validate-data.adoc[].

[TIP]
====
An important **prerequisite** is that you already have the matching schema on the target database. For every table migrated by Cassandra Data Migrator, the tool takes a mapping configuration that links every origin column to every target column.
====

The validation checks are a way to verify that all the data has been migrated successfully.

=== Example

Consider the following example:

* Origin table: `User` with fields `id uuid, first_name text, last_name text, age int`
* Target table: `Customer` with fields `cust_id uuid, fn text, ln text, contact text`

In this example, the schema is not identical. However, mapping the fields is possible to enable the data migration. That is, map `User` to `Customer`; map `id` to `cust_id`; map `first_name` to `fn`, and so on. The data for this scenario can be migrated. You would need to first define define this mapping in the config file used by {cstar-data-migrator}.

**TODO**: In the xref:migration-migrate-and-validate-data.adoc[] topic, provide details on how the mapping is defined in a config file.

=== Infrastructure required on your Origin cluster

Refer to xref:migration-deployment-infrastructure.adoc[].
