= Configure Transport Layer Security (TLS)

{zdm-proxy} supports proxy-to-cluster TLS connections, and application-to-proxy TLS connections.  

The TLS configuration is an optional part of the initial {zdm-proxy} configuration. See the information here in this topic, and then refer to the {zdm-automation} topics that cover:

* xref:migration-setup-ansible-playbooks.adoc[]
* xref:migration-run-ansible-playbooks.adoc[]

== Introduction

* For proxy-to-cluster TLS, origin and/or target cluster, the {zdm-proxy} acts as the TLS client and the cluster as the TLS server. One-way TLS and Mutual TLS are both supported. 

* For application-to-proxy TLS, the application is the TLS client and the {zdm-proxy} is the TLS server. One-way TLS and Mutual TLS are both supported.

* When the {zdm-proxy} connects to Astra DB clusters, it always implicitly uses Mutual TLS. 
This is done through the Secure Connect Bundle (SCB) and does not require any extra configuration.

== Proxy to self-managed cluster TLS

Here's how to configure TLS between the {zdm-proxy} and a self-managed cluster. The configuration is the same for an origin and/or target cluster. 

The assets required to configure TLS are:

* Server CA certificate: needed for one-way and mTLS
* Client certificate: only needed for mTLS
* Client key: only needed for mTLS

=== Retrieving assets from a JKS keystore

The {zdm-proxy} does not accept a JKS keystore, requiring the raw files instead.

To view the files contained in a keystore and their aliases:

```bash
keytool -list -keystore <path_to_keystore.jks>
```

To extract a file from a JKS repository:

```
keytool -exportcert -keystore <path_to_jks_store> -alias <file_alias> -file <path_to_destination_file> -rfc
```

Please note the `-rfc` option, which extracts the files in non-binary PEM format.

For more details, see the https://docs.oracle.com/javase/8/docs/technotes/tools/windows/keytool.html[keytool syntax documentation^].

=== Prepare the TLS assets

For each TLS-enabled cluster (origin and/or target), create a directory on the Ansible Control Host (for example, `origin_tls_assets` and / or `target_tls_assets`). This directory is only needed for self-managed clusters requiring TLS.

Copy the necessary TLS files to each directory:

* For one-way TLS, only the Server CA cert.

* For mTLS, the Server CA cert + the client cert and client key.

Edit the relevant values in the configuration file `vars/proxy_custom_tls_config_input.yml` as follows.

* For proxy-to-Origin TLS configuration:

 ** `origin_tls_user_dir_path_name`: path to the directory on the Ansible Control Host containing the TLS assets for Origin; for example, `/home/ubuntu/origin_tls_assets`.

 ** `origin_tls_server_ca_filename`: filename (without path) of the Server CA.

 ** `origin_tls_client_cert_filename`: filename (without path) of the Client cert. For mTLS only, leave unset otherwise.

 ** `origin_tls_client_key_filename`: filename (without path) of the Client key. For mTLS only, leave unset otherwise.

* The configuration for proxy-to-Target TLS is done in the same way but using the target-specific configuration parameters (`target_tls_*`).

== Application-to-proxy TLS

To configure application-to-proxy TLS you need to:

* Create a directory on the jumphost (for example `/home/ubuntu/proxy_tls_assets`) and copy all necessary TLS assets to it.

* Populate the relevant variables in `vars/proxy_custom_tls_config_input.yml` as explained below.

* Run the deployment playbook (`zdm_proxy_playbook.yml`) as usual. The playbook will distribute the assets to each proxy instance and apply the TLS configuration to it.

The relevant variables are in the bottom section of `vars/proxy_custom_tls_config_input.yml` and are all prefixed with `proxy_` :

* `proxy_tls_user_dir_path_name`: directory on the Ansible Control Host where you placed all the necessary TLS assets for application-to-proxy TLS. Always required.

* `proxy_tls_server_ca_filename`:  filename (without path) of the server CA that the proxy must use. Always required.

* `proxy_tls_server_cert_filename` and `proxy_tls_server_key_filename` : filenames (without path) of the server certificate and server key that the proxy must use. Both always required.

* `proxy_tls_require_client_auth`: whether you want to enable Mutual TLS between the application and the proxy. Optional: defaults to `false` ( = one-way TLS ), can be set to true to enable mTLS.

[TIP]
====
Remember that in this case, the {zdm-proxy} is the TLS server; thus the word `server` word in these variable names.
====

== What's next?

Learn how to xref:migration-prepare-environment.adoc[].

