= DataStax Zero Downtime Migration Release Notes

The {company} {zdm-product} (ZDM) project provides a production-ready set of tools to help you migrate to another version of Apache Cassandra&reg; or DataStax Enterprise, or to cloud-native Astra DB.

== Release Notes for ZDM 2.0.0

18 October 2022

== Components and GitHub repos

All the {company} {zdm-product} repos are public. You are welcome to read the source and submit feedback via GitHub Issues per repo.

* https://github.com/datastax/zdm-proxy[{zdm-proxy}^] open-source repo: in addition to sending feedback, you may submit Pull Requests (PRs) on a fork, for potential inclusion. See xref:migration-contributions.adoc[].

* https://github.com/datastax/zdm-proxy-automation[{zdm-automation}^] repo for automation via Ansible playbooks.

* https://github.com/datastax/cassandra-data-migrator[{cstar-data-migrator}^] repo for migrating and validating data.

* This https://github.com/datastax/migration-docs[Migration documentation^] repo.

=== Supported environments

With the {company} {zdm-product} 2.0.0 release, you can migrate any Cassandra Query Language (CQL) compliant database cluster from its origin (current) environment to a new target. Migration examples:

* From an existing self-managed Cassandra or DSE cluster to cloud-native Astra DB or vice versa. For example, migrate:
** Cassandra 3.11.x or 4.0.x to Astra DB
** DSE 5.1.x or 6.8.x to Astra DB
* From an existing Cassandra or DSE cluster to another Cassandra or DSE cluster. For example, migrate:
** Cassandra 3.11.x to 4.0.x
** DSE 5.1.x to DSE 6.8.x
* From Astra DB Classic to Astra DB Serverless

=== {zdm-proxy} 2.0.0 revisions

See the https://github.com/datastax/zdm-proxy/blob/main/CHANGELOG/CHANGELOG-2.0.md(CHANGELOG-2.0^) (to-be-generated) for details about the {zdm-proxy} open-source code.

