= {company} {zdm-product} Release Notes

== ZDM 2.0 release

18 October 2022

== Components and GitHub repos

The following {company} {zdm-product} GitHub repos are public. You are welcome to read the source and submit feedback via GitHub Issues per repo.

* https://github.com/datastax/zdm-proxy[{zdm-proxy}^] open-source repo: in addition to sending feedback, you may submit Pull Requests (PRs) for potential inclusion, provided you accept the https://cla.datastax.com/[{company} Contributor License Agreement (CLA)^]. For more information, see xref:contributions.adoc[].

* https://github.com/datastax/zdm-proxy-automation[{zdm-automation}^] repo for Ansible-based {zdm-proxy} automation.

* https://github.com/datastax/dsbulk-migrator[DSBulk Migrator^] repo for migration of smaller data quantities.

* https://github.com/datastax/cassandra-data-migrator[Cassandra Data Migrator^] repo for migration of larger data quantities and where detailed verifications and reconciliation options are needed.

include::partial$note-downtime.adoc[]

====
[TIP]
The {zdm-product} process requires you to be able to perform rolling restarts of your client applications during the migration. This is standard practice for client applications that are deployed over multiple instances and is a widely used approach to roll out releases and configuration changes.
====

== Supported releases

include::partial$supported-releases.adoc[]

== Migration scenarios

include::partial$migration-scenarios.adoc[]

== {zdm-proxy} 2.0 revisions

For the latest information about {zdm-proxy} new features and other changes, please refer to the GitHub-hosted https://github.com/datastax/zdm-proxy/blob/main/RELEASE_NOTES.md[RELEASE_NOTES^] in the open-source {zdm-proxy} repo. The document includes CHANGELOG links for each `N.n` release.
