[cols="3,1,5a"]
|===
|Property | Default | Notes

| `spark.cdm.schema.origin.keyspaceTable`
| 
| Required - the `<keyspace>.<table_name>` of the table to be migrated.
Table must exist in the origin cluster.

| `spark.cdm.schema.origin.column.ttl.automatic`
| `true`
| Default is `true`, unless `spark.cdm.schema.origin.column.ttl.names` is specified.
When `true`, determine the Time To Live (TTL) of the target record. 
Find the maximum TTL of all origin columns that can have TTL set. This excludes partition key, clustering key, collections/UDT/tuple, and frozen columns.
When `false`, and  `spark.cdm.schema.origin.column.ttl.names` is not set, the target record has the target table configuration determine the TTL.  

| `spark.cdm.schema.origin.column.ttl.names`
| 
| Default is empty, meaning the names are determined automatically if `spark.cdm.schema.origin.column.ttl.automatic` is set.
Specify a subset of eligible columns that are used to calculate the TTL of the target record.

| `spark.cdm.schema.origin.column.writetime.automatic`
| `true`
| Default is `true`, unless `spark.cdm.schema.origin.column.writetime.names` is specified.
When `true`, determine the `WRITETIME` of the target record. 
Find the maximum `WRITETIME` of all origin columns that can have `WRITETIME` set. This excludes partition key, clustering key, collections/UDT/tuple, and frozen columns.
When `false`, and `spark.cdm.schema.origin.column.writetime.names` is not set, the target table configuration determines the target record's `WRITETIME`. 

[NOTE]
====
The `spark.cdm.transform.custom.writetime` property, if set, overrides `spark.cdm.schema.origin.column.writetime`.
====

| `spark.cdm.schema.origin.column.writetime.names`
| 
| Default is empty, meaning the names are determined automatically if `spark.cdm.schema.origin.column.writetime.automatic` is set.
Otherwise, specify a subset of eligible columns that are used to calculate the WRITETIME of the target record.
Example: `data_col1,data_col2,...`

| `spark.cdm.schema.origin.column.names.to.target`
| 
| Default is empty.
If column names are changed between the origin and target clusters, then this mapped list provides a mechanism to associate the two.
The format is `<origin_column_name>:<target_column_name>`.
The list is comma separated.
You only need to list renamed columns. 

|===

[NOTE]
====
For optimization reasons, {cstar-data-migrator} does not migrate TTL and writetime at the field level.
Instead, {cstar-data-migrator} finds the field with the highest TTL and the field with the highest writetime within an origin table row, and uses those values on the entire target table row.
====